
import { MealOption, ActivityType, MealMoment, Language } from './types';

export const MEAL_MOMENTS: MealMoment[] = [
  'Ontbijt',
  'Ochtend snack',
  'Lunch',
  'Middag snack',
  'Diner',
  'Avondsnack'
];

export const PRODUCT_TRANSLATIONS: Record<Language, Record<string, string>> = {
  nl: {
    d_water: 'Water (250 ml)',
    d_koffie: 'Koffie (Zwart, 200 ml)',
    d_thee: 'Thee (Zonder suiker, 200 ml)',
    d_melk_half: 'Melk (Halfvol, 250 ml)',
    d_melk_vol: 'Melk (Vol, 250 ml)',
    d_sap_pak: 'Sinaasappelsap (Pak, 250 ml)',
    d_sap_vers: 'Sinaasappelsap (Vers, 250 ml)',
    d_cappuccino: 'Cappuccino (200 ml)',
    d_latte: 'Latte Macchiato (250 ml)',
    d_cola: 'Cola (Regular, 250 ml)',
    d_cola_zero: 'Cola Zero (250 ml)',
    d_icetea: 'Ice Tea (250 ml)',
    d_appelsap: 'Appelsap (250 ml)',
    a_bier: 'Bier (330 ml)',
    a_wijn_wit: 'Witte Wijn (Droog, 150 ml)',
    a_wijn_rood: 'Rode Wijn (150 ml)',
    a_wijn_rose: 'Rosé Wijn (150 ml)',
    a_gin_tonic: 'Gin-Tonic (250 ml)',
    a_whiskey: 'Whiskey (35 ml)',
    a_wodka: 'Wodka (35 ml)',
    c_water_spelen: 'Zwemmen/ spelen in water',
    c_proteine_lepel: 'Proteine (Eetlepel)',
    c_rijstkoek_lidl: 'Rijstenkoek (Lidl)',
    c_volkoren_cracker_lidl: 'Volkoren Cracker (Lidl)',
    c_tomatensoep_300: 'Zelfgemaakte tomatensoep (300 ml)',
    c_pindakaas_lepel: 'Pindakaas (Eetlepel)',
    c_zilvervlies_ongekookt: 'Zilvervliesrijst ongekookt (100 gr)',
    c_zilvervlies_gekookt: 'Zilvervliesrijst gekookt (100 gr)',
    c_r3uszie7o: 'Smeerkaas op Cracker',
    o1: 'Magere kwark (per 100g)',
    o2: 'Gekookt ei',
    o3: 'Volkoren cracker (Wasa)',
    l_b1: 'Volkoren boterham',
    d1: 'Nasi/Bami Groenten (500g)',
    wandelen_5: 'Wandelen (5 km per uur)',
    wandelen_tempo: 'Wandelen (stevig tempo)',
    hardlopen: 'Hardlopen (10 km/u)',
    fietsen: 'Fietsen (rustig)',
    zwemmen: 'Zwemmen (recreatief)',
    padellen: 'Padellen',
    krachttraining: 'Krachttraining / Fitness',
  },
  en: {
    d_water: 'Water (250 ml)',
    d_koffie: 'Coffee (Black, 200 ml)',
    d_thee: 'Tea (Unsweetened, 200 ml)',
    d_melk_half: 'Milk (Semi-skimmed, 250 ml)',
    d_melk_vol: 'Milk (Whole, 250 ml)',
    d_sap_pak: 'Orange Juice (Carton, 250 ml)',
    d_sap_vers: 'Orange Juice (Fresh, 250 ml)',
    d_cappuccino: 'Cappuccino (200 ml)',
    d_latte: 'Latte Macchiato (250 ml)',
    d_cola: 'Cola (Regular, 250 ml)',
    d_cola_zero: 'Cola Zero (250 ml)',
    d_icetea: 'Ice Tea (250 ml)',
    d_appelsap: 'Apple Juice (250 ml)',
    a_bier: 'Beer (330 ml)',
    a_wijn_wit: 'White Wine (Dry, 150 ml)',
    a_wijn_rood: 'Red Wine (150 ml)',
    a_wijn_rose: 'Rosé Wine (150 ml)',
    a_gin_tonic: 'Gin-Tonic (250 ml)',
    a_whiskey: 'Whiskey (35 ml)',
    a_wodka: 'Vodka (35 ml)',
    c_water_spelen: 'Swimming / playing in water',
    c_proteine_lepel: 'Protein (Tablespoon)',
    c_rijstkoek_lidl: 'Rice Cake (Lidl)',
    c_volkoren_cracker_lidl: 'Whole Wheat Cracker (Lidl)',
    c_tomatensoep_300: 'Homemade Tomato Soup (300 ml)',
    c_pindakaas_lepel: 'Peanut Butter (Tablespoon)',
    c_zilvervlies_ongekookt: 'Brown Rice uncooked (100 gr)',
    c_zilvervlies_gekookt: 'Brown Rice cooked (100 gr)',
    c_r3uszie7o: 'Cheese Spread on Cracker',
    o1: 'Low-fat Quark (per 100g)',
    o2: 'Boiled egg',
    o3: 'Whole wheat cracker (Wasa)',
    l_b1: 'Whole wheat bread slice',
    d1: 'Stir-fry Vegetables (500g)',
    wandelen_5: 'Walking (5 km/h)',
    wandelen_tempo: 'Walking (brisk pace)',
    hardlopen: 'Running (10 km/h)',
    fietsen: 'Cycling (casual)',
    zwemmen: 'Swimming (recreational)',
    padellen: 'Padel',
    krachttraining: 'Weight Training / Fitness',
  },
  es: {
    d_water: 'Agua (250 ml)',
    d_koffie: 'Café (Solo, 200 ml)',
    d_thee: 'Té (Sin azúcar, 200 ml)',
    d_melk_half: 'Leche (Semidesnatada, 250 ml)',
    d_melk_vol: 'Leche (Entera, 250 ml)',
    d_sap_pak: 'Zumo de Naranja (Cartón, 250 ml)',
    d_sap_vers: 'Zumo de Naranja (Natural, 250 ml)',
    d_cappuccino: 'Capuchino (200 ml)',
    d_latte: 'Latte Macchiato (250 ml)',
    d_cola: 'Cola (Regular, 250 ml)',
    d_cola_zero: 'Cola Zero (250 ml)',
    d_icetea: 'Té Helado (250 ml)',
    d_appelsap: 'Zumo de Manzana (250 ml)',
    a_bier: 'Cerveza (330 ml)',
    a_wijn_wit: 'Vino Blanco (150 ml)',
    a_wijn_rood: 'Vino Tinto (150 ml)',
    a_wijn_rose: 'Vino Rosado (150 ml)',
    a_gin_tonic: 'Gin-Tonic (250 ml)',
    a_whiskey: 'Whisky (35 ml)',
    a_wodka: 'Vodka (35 ml)',
    c_water_spelen: 'Nadar / jugar en el agua',
    c_proteine_lepel: 'Proteína (Cucharada)',
    c_rijstkoek_lidl: 'Tortita de Arroz (Lidl)',
    c_volkoren_cracker_lidl: 'Crackers Integrales (Lidl)',
    c_tomatensoep_300: 'Sopa de Tomate Casera (300 ml)',
    c_pindakaas_lepel: 'Mantequilla de Cacahuete (Cucharada)',
    c_zilvervlies_ongekookt: 'Arroz integral crudo (100 gr)',
    c_zilvervlies_gekookt: 'Arroz integral cocido (100 gr)',
    c_r3uszie7o: 'Queso crema en cracker',
    o1: 'Queso Quark desnatado (por 100g)',
    o2: 'Huevo cocido',
    o3: 'Cracker integral (Wasa)',
    l_b1: 'Pan integral',
    d1: 'Verduras al wok (500g)',
    wandelen_5: 'Caminar (5 km/h)',
    wandelen_tempo: 'Caminar (ritmo rápido)',
    hardlopen: 'Correr (10 km/h)',
    fietsen: 'Ciclismo (tranquilo)',
    zwemmen: 'Natación (recreativa)',
    padellen: 'Pádel',
    krachttraining: 'Entrenamiento de pesas',
  },
  de: {
    d_water: 'Wasser (250 ml)',
    d_koffie: 'Kaffee (Schwarz, 200 ml)',
    d_thee: 'Tee (Ungesüßt, 200 ml)',
    d_melk_half: 'Milch (Fettarm, 250 ml)',
    d_melk_vol: 'Milch (Vollmilch, 250 ml)',
    d_sap_pak: 'Orangensaft (Packung, 250 ml)',
    d_sap_vers: 'Orangensaft (Frisch, 250 ml)',
    d_cappuccino: 'Cappuccino (200 ml)',
    d_latte: 'Latte Macchiato (250 ml)',
    d_cola: 'Cola (Normal, 250 ml)',
    d_cola_zero: 'Cola Zero (250 ml)',
    d_icetea: 'Eistee (250 ml)',
    d_appelsap: 'Apfelsaft (250 ml)',
    a_bier: 'Bier (330 ml)',
    a_wijn_wit: 'Weißwein (150 ml)',
    a_wijn_rood: 'Rotwein (150 ml)',
    a_wijn_rose: 'Roséwein (150 ml)',
    a_gin_tonic: 'Gin-Tonic (250 ml)',
    a_whiskey: 'Whiskey (35 ml)',
    a_wodka: 'Wodka (35 ml)',
    c_water_spelen: 'Schwimmen / im Wasser spielen',
    c_proteine_lepel: 'Protein (Esslöffel)',
    c_rijstkoek_lidl: 'Reiswaffel (Lidl)',
    c_volkoren_cracker_lidl: 'Vollkorncracker (Lidl)',
    c_tomatensoep_300: 'Hausgemachte Tomatensuppe (300 ml)',
    c_pindakaas_lepel: 'Erdnussbutter (Esslöffel)',
    c_zilvervlies_ongekookt: 'Naturreis ungekocht (100 gr)',
    c_zilvervlies_gekookt: 'Naturreis gekocht (100 gr)',
    c_r3uszie7o: 'Streichkäse auf Cracker',
    o1: 'Magerquark (pro 100g)',
    o2: 'Gekochtes Ei',
    o3: 'Vollkorncracker (Wasa)',
    l_b1: 'Vollkornbrot',
    d1: 'Wok-Gemüse (500g)',
    wandelen_5: 'Gehen (5 km/h)',
    wandelen_tempo: 'Schnelles Gehen',
    hardlopen: 'Laufen (10 km/h)',
    fietsen: 'Radfahren (entspannt)',
    zwemmen: 'Schwimmen (Freizeit)',
    padellen: 'Padel-Tennis',
    krachttraining: 'Krafttraining / Fitness',
  },
  zh: {
    d_water: '水 (250 毫升)',
    d_koffie: '黑咖啡 (200 毫升)',
    d_thee: '茶 (无糖, 200 毫升)',
    d_melk_half: '半脱脂牛奶 (250 毫升)',
    d_melk_vol: '全脂牛奶 (250 毫升)',
    d_sap_pak: '橙汁 (盒装, 250 毫升)',
    d_sap_vers: '鲜榨橙汁 (250 毫升)',
    d_cappuccino: '卡布奇诺 (200 毫升)',
    d_latte: '拿铁玛奇朵 (250 毫升)',
    d_cola: '可乐 (常规, 250 毫升)',
    d_cola_zero: '零度可乐 (250 毫升)',
    d_icetea: '冰茶 (250 毫升)',
    d_appelsap: '苹果汁 (250 毫升)',
    a_bier: '啤酒 (330 毫升)',
    a_wijn_wit: '白葡萄酒 (150 毫升)',
    a_wijn_rood: '红葡萄酒 (150 毫升)',
    a_wijn_rose: '桃红葡萄酒 (150 毫升)',
    a_gin_tonic: '金汤力 (250 毫升)',
    a_whiskey: '威士忌 (35 毫升)',
    a_wodka: '伏特加 (35 毫升)',
    c_water_spelen: '游泳/水中嬉戏',
    c_proteine_lepel: '蛋白粉 (汤匙)',
    c_rijstkoek_lidl: '米饼 (Lidl)',
    c_volkoren_cracker_lidl: '全麦饼干 (Lidl)',
    c_tomatensoep_300: '自制番茄汤 (300 毫升)',
    c_pindakaas_lepel: '花生酱 (汤匙)',
    c_zilvervlies_ongekookt: '糙米未煮 (100 克)',
    c_zilvervlies_gekookt: '糙米煮熟 (100 克)',
    c_r3uszie7o: '饼干涂抹干酪',
    o1: '低脂夸克乳酪 (每 100 克)',
    o2: '煮鸡蛋',
    o3: '全麦饼干 (Wasa)',
    l_b1: '全麦面包',
    d1: '炒蔬菜 (500 克)',
    wandelen_5: '步行 (5 公里/小时)',
    wandelen_tempo: '快步走',
    hardlopen: '跑步 (10 公里/小时)',
    fietsen: '骑行 (休闲)',
    zwemmen: '游泳 (娱乐性)',
    padellen: '板式网球',
    krachttraining: '力量训练 / 健身',
  },
  ja: {
    d_water: '水 (250 ml)',
    d_koffie: 'ブラックコーヒー (200 ml)',
    d_thee: 'お茶 (無糖, 200 ml)',
    d_melk_half: '低脂肪乳 (250 ml)',
    d_melk_vol: '牛乳 (250 ml)',
    d_sap_pak: 'オレンジジュース (パック, 250 ml)',
    d_sap_vers: '生搾りオレンジジュース (250 ml)',
    d_cappuccino: 'カプチーノ (200 ml)',
    d_latte: 'ラテ・マキアート (250 ml)',
    d_cola: 'コーラ (レギュラー, 250 ml)',
    d_cola_zero: 'コーラ・ゼロ (250 ml)',
    d_icetea: 'アイスティー (250 ml)',
    d_appelsap: 'アップルジュース (250 ml)',
    a_bier: 'ビール (330 ml)',
    a_wijn_wit: '白ワイン (150 ml)',
    a_wijn_rood: '赤ワイン (150 ml)',
    a_wijn_rose: 'ロゼワイン (150 ml)',
    a_gin_tonic: 'ジントニック (250 ml)',
    a_whiskey: 'ウイスキー (35 ml)',
    a_wodka: 'ウォッカ (35 ml)',
    c_water_spelen: '水泳/水遊び',
    c_proteine_lepel: 'プロテイン (大さじ1)',
    c_rijstkoek_lidl: 'ライスケーキ (Lidl)',
    c_volkoren_cracker_lidl: '全粒粉クラッカー (Lidl)',
    c_tomatensoep_300: '自家製トマトスープ (300 ml)',
    c_pindakaas_lepel: 'ピーナッツバター (大さじ1)',
    c_zilvervlies_ongekookt: '玄米 生 (100g)',
    c_zilvervlies_gekookt: '玄米 炊飯後 (100g)',
    c_r3uszie7o: 'クラッカーのチーズ乗せ',
    o1: '低脂肪クワルク (100gあたり)',
    o2: 'ゆで卵',
    o3: '全粒粉クラッカー (Wasa)',
    l_b1: '全粒粉食パン',
    d1: '野菜炒め (500g)',
    wandelen_5: 'ウォーキング (時速5km)',
    wandelen_tempo: '早歩き',
    hardlopen: 'ランニング (時速10km)',
    fietsen: 'サイクリング (ゆっくり)',
    zwemmen: '水泳 (レクリエーション)',
    padellen: 'パデル',
    krachttraining: '筋トレ / フィットネス',
  },
  ko: {
    d_water: '물 (250 ml)',
    d_koffie: '블랙 커피 (200 ml)',
    d_thee: '차 (무설탕, 200 ml)',
    d_melk_half: '저지방 우유 (250 ml)',
    d_melk_vol: '일반 우유 (250 ml)',
    d_sap_pak: '오렌지 주스 (팩, 250 ml)',
    d_sap_vers: '생 오렌지 주스 (250 ml)',
    d_cappuccino: '카푸치노 (200 ml)',
    d_latte: '라떼 마키아토 (250 ml)',
    d_cola: '콜라 (일반, 250 ml)',
    d_cola_zero: '콜라 제로 (250 ml)',
    d_icetea: '아이스티 (250 ml)',
    d_appelsap: '사과 주스 (250 ml)',
    a_bier: '맥주 (330 ml)',
    a_wijn_wit: '화이트 와인 (150 ml)',
    a_wijn_rood: '레드 와인 (150 ml)',
    a_wijn_rose: '로제 와인 (150 ml)',
    a_gin_tonic: '진토닉 (250 ml)',
    a_whiskey: '위스키 (35 ml)',
    a_wodka: '보드카 (35 ml)',
    c_water_spelen: '수영 / 물놀이',
    c_proteine_lepel: '단백질 (한 큰술)',
    c_rijstkoek_lidl: '쌀과자 (Lidl)',
    c_volkoren_cracker_lidl: '통밀 크래커 (Lidl)',
    c_tomatensoep_300: '수제 토마토 수프 (300 ml)',
    c_pindakaas_lepel: '땅콩 버터 (한 큰술)',
    c_zilvervlies_ongekookt: '현미 생쌀 (100g)',
    c_zilvervlies_gekookt: '현미 밥 (100g)',
    c_r3uszie7o: '크래커와 치즈 스프레드',
    o1: '저지방 쿼크 (100g당)',
    o2: '삶은 계란',
    o3: '통밀 크래커 (Wasa)',
    l_b1: '통밀 식빵',
    d1: '야채 볶음 (500g)',
    wandelen_5: '걷기 (5 km/h)',
    wandelen_tempo: '빠르게 걷기',
    hardlopen: '달리기 (10 km/h)',
    fietsen: '자전거 타기 (여유롭게)',
    zwemmen: '수영 (취미)',
    padellen: '파델',
    krachttraining: '근력 운동 / 피트니스',
  },
  hi: {
    d_water: 'पानी (250 ml)',
    d_koffie: 'कॉफी (काली, 200 ml)',
    d_thee: 'चाय (बिना चीनी, 200 ml)',
    d_melk_half: 'दूध (कम वसा, 250 ml)',
    d_melk_vol: 'दूध (पूर्ण वसा, 250 ml)',
    d_sap_pak: 'संतरे का जूस (पैक, 250 ml)',
    d_sap_vers: 'संतरे का जूस (ताज़ा, 250 ml)',
    d_cappuccino: 'कैपुचीनो (200 ml)',
    d_latte: 'लाते माकियातो (250 ml)',
    d_cola: 'कोला (सामान्य, 250 ml)',
    d_cola_zero: 'कोला जीरो (250 ml)',
    d_icetea: 'आइस टी (250 ml)',
    d_appelsap: 'सेब का जूस (250 ml)',
    a_bier: 'बीयर (330 ml)',
    a_wijn_wit: 'व्हाइट वाइन (150 ml)',
    a_wijn_rood: 'रेड वाइन (150 ml)',
    a_wijn_rose: 'रोज़ वाइन (150 ml)',
    a_gin_tonic: 'जिन-टॉनिक (250 ml)',
    a_whiskey: 'व्हिस्की (35 ml)',
    a_wodka: 'वोदका (35 ml)',
    c_water_spelen: 'तैरना / पानी में खेलना',
    c_proteine_lepel: 'प्रोटीन (एक बड़ा चम्मच)',
    c_rijstkoek_lidl: 'चावल का केक (Lidl)',
    c_volkoren_cracker_lidl: 'होल व्हीट क्रैकर (Lidl)',
    c_tomatensoep_300: 'घर का बना टमाटर सूप (300 ml)',
    c_pindakaas_lepel: 'मूंगफली का मक्खन (बड़ा चम्मच)',
    c_zilvervlies_ongekookt: 'ब्राउन राइस बिना पका (100 gr)',
    c_zilvervlies_gekookt: 'ब्राउन राइस पका हुआ (100 gr)',
    c_r3uszie7o: 'क्रैकर पर पनीर',
    o1: 'कम वसा वाला दही (प्रति 100g)',
    o2: 'उबला हुआ अंडा',
    o3: 'होल व्हीट क्रैकर (Wasa)',
    l_b1: 'होल व्हीट ब्रेड',
    d1: 'सब्जी स्टिर-फ्राई (500g)',
    wandelen_5: 'पैदल चलना (5 km/h)',
    wandelen_tempo: 'तेज़ चलना',
    hardlopen: 'दौड़ना (10 km/h)',
    fietsen: 'साइकिल चलाना (आराम से)',
    zwemmen: 'तैरना (मनोरंजक)',
    padellen: 'पेडल टेनिस',
    krachttraining: 'वेट ट्रेनिंग / फिटनेस',
  },
  ar: {
    d_water: 'ماء (250 مل)',
    d_koffie: 'قهوة سوداء (200 مل)',
    d_thee: 'شاي (بدون سكر, 200 مل)',
    d_melk_half: 'حليب نصف دسم (250 مل)',
    d_melk_vol: 'حليب كامل الدسم (250 مل)',
    d_sap_pak: 'عصير برتقال (علبة, 250 مل)',
    d_sap_vers: 'عصير برتقال طازج (250 مل)',
    d_cappuccino: 'كابتشينو (200 مل)',
    d_latte: 'لاتيه ماكياتو (250 مل)',
    d_cola: 'كولا (عادي, 250 مل)',
    d_cola_zero: 'كولا زيرو (250 مل)',
    d_icetea: 'شاي مثلج (250 مل)',
    d_appelsap: 'عصير تفاح (250 مل)',
    a_bier: 'بيرة (330 مل)',
    a_wijn_wit: 'نبيذ أبيض (150 مل)',
    a_wijn_rood: 'نبيذ أحمر (150 مل)',
    a_wijn_rose: 'نبيذ روزيه (150 مل)',
    a_gin_tonic: 'جين وتونيك (250 مل)',
    a_whiskey: 'ويسكى (35 مل)',
    a_wodka: 'فودكا (35 مل)',
    c_water_spelen: 'سباحة / لعب في الماء',
    c_proteine_lepel: 'بروتين (ملعقة كبيرة)',
    c_rijstkoek_lidl: 'كعكة أرز (Lidl)',
    c_volkoren_cracker_lidl: 'بسكويت قمح كامل (Lidl)',
    c_tomatensoep_300: 'شوربة طماطم منزلية (300 مل)',
    c_pindakaas_lepel: 'زبدة فول سوداني (ملعقة)',
    c_zilvervlies_ongekookt: 'أرز بني غير مطبوخ (100 جم)',
    c_zilvervlies_gekookt: 'أرز بني مطبوخ (100 جم)',
    c_r3uszie7o: 'جبنة قابلة للدهن على بسكويت',
    o1: 'كوارك قليل الدسم (لكل 100 جم)',
    o2: 'بيضة مسلوقة',
    o3: 'بسكويت قمح كامل (Wasa)',
    l_b1: 'خبز قمح كامل',
    d1: 'خضار مقلية (500 جم)',
    wandelen_5: 'مشي (5 كم/ساعة)',
    wandelen_tempo: 'مشي سريع',
    hardlopen: 'جري (10 كم/ساعة)',
    fietsen: 'ركوب دراجات (هادئ)',
    zwemmen: 'سباحة (ترفيهية)',
    padellen: 'بادل',
    krachttraining: 'تدريب أثقال / لياقة',
  },
  pt: {
    d_water: 'Água (250 ml)',
    d_koffie: 'Café (Preto, 200 ml)',
    d_thee: 'Chá (Sem açúcar, 200 ml)',
    d_melk_half: 'Leite (Meio-gordo, 250 ml)',
    d_melk_vol: 'Leite (Gordo, 250 ml)',
    d_sap_pak: 'Sumo de Laranja (Pacote, 250 ml)',
    d_sap_vers: 'Sumo de Laranja (Natural, 250 ml)',
    d_cappuccino: 'Cappuccino (200 ml)',
    d_latte: 'Latte Macchiato (250 ml)',
    d_cola: 'Cola (Normal, 250 ml)',
    d_cola_zero: 'Cola Zero (250 ml)',
    d_icetea: 'Chá Gelado (250 ml)',
    d_appelsap: 'Sumo de Maçã (250 ml)',
    a_bier: 'Cerveja (330 ml)',
    a_wijn_wit: 'Vinho Branco (150 ml)',
    a_wijn_rood: 'Vinho Tinto (150 ml)',
    a_wijn_rose: 'Vinho Rosé (150 ml)',
    a_gin_tonic: 'Gin-Tônico (250 ml)',
    a_whiskey: 'Whisky (35 ml)',
    a_wodka: 'Vodka (35 ml)',
    c_water_spelen: 'Nadar / brincar na água',
    c_proteine_lepel: 'Proteína (Colher de sopa)',
    c_rijstkoek_lidl: 'Bolacha de Arroz (Lidl)',
    c_volkoren_cracker_lidl: 'Bolacha Integral (Lidl)',
    c_tomatensoep_300: 'Sopa de Tomate Caseira (300 ml)',
    c_pindakaas_lepel: 'Manteiga de Amendoim (Colher)',
    c_zilvervlies_ongekookt: 'Arroz Integral cru (100 gr)',
    c_zilvervlies_gekookt: 'Arroz Integral cozido (100 gr)',
    c_r3uszie7o: 'Queijo creme em bolacha',
    o1: 'Queijo Quark magro (por 100g)',
    o2: 'Ovo cozido',
    o3: 'Bolacha integral (Wasa)',
    l_b1: 'Pão integral',
    d1: 'Legumes salteados (500g)',
    wandelen_5: 'Caminhar (5 km/h)',
    wandelen_tempo: 'Caminhar rápido',
    hardlopen: 'Corrida (10 km/h)',
    fietsen: 'Ciclismo (lazer)',
    zwemmen: 'Natação (recreativa)',
    padellen: 'Padel',
    krachttraining: 'Musculação / Fitness',
  },
};

const COMMON_DRINKS: MealOption[] = [
  { id: 'd_water', name: 'Water (250 ml)', kcal: 0, isDrink: true },
  { id: 'd_koffie', name: 'Koffie (Zwart, 200 ml)', kcal: 2, isDrink: true },
  { id: 'd_thee', name: 'Thee (Zonder suiker, 200 ml)', kcal: 2, isDrink: true },
  { id: 'd_melk_half', name: 'Melk (Halfvol, 250 ml)', kcal: 115, isDrink: true },
  { id: 'd_melk_vol', name: 'Melk (Vol, 250 ml)', kcal: 160, isDrink: true },
  { id: 'd_sap_pak', name: 'Sinaasappelsap (Pak, 250 ml)', kcal: 110, isDrink: true },
  { id: 'd_sap_vers', name: 'Sinaasappelsap (Vers, 250 ml)', kcal: 115, isDrink: true },
  { id: 'd_cappuccino', name: 'Cappuccino (200 ml)', kcal: 80, isDrink: true },
  { id: 'd_latte', name: 'Latte Macchiato (250 ml)', kcal: 120, isDrink: true },
  { id: 'd_cola', name: 'Cola (Regular, 250 ml)', kcal: 105, isDrink: true },
  { id: 'd_cola_zero', name: 'Cola Zero (250 ml)', kcal: 0, isDrink: true },
  { id: 'd_icetea', name: 'Ice Tea (250 ml)', kcal: 70, isDrink: true },
  { id: 'd_appelsap', name: 'Appelsap (250 ml)', kcal: 115, isDrink: true },
];

const ALCOHOLIC_DRINKS: MealOption[] = [
  { id: 'a_bier', name: 'Bier (330 ml)', kcal: 140, isDrink: true },
  { id: 'a_wijn_wit', name: 'Witte Wijn (Droog, 150 ml)', kcal: 100, isDrink: true },
  { id: 'a_wijn_rood', name: 'Rode Wijn (150 ml)', kcal: 120, isDrink: true },
  { id: 'a_wijn_rose', name: 'Rosé Wijn (150 ml)', kcal: 105, isDrink: true },
  { id: 'a_gin_tonic', name: 'Gin-Tonic (250 ml)', kcal: 170, isDrink: true },
  { id: 'a_whiskey', name: 'Whiskey (35 ml)', kcal: 85, isDrink: true },
  { id: 'a_wodka', name: 'Wodka (35 ml)', kcal: 75, isDrink: true },
];

export const MEAL_OPTIONS: Record<MealMoment, MealOption[]> = {
  'Ontbijt': [
    ...COMMON_DRINKS,
    { id: 'c_pindakaas_lepel', name: 'Pindakaas (Eetlepel)', kcal: 95, isCustom: true },
    { id: 'c_r3uszie7o', name: 'Smeerkaas op Cracker', kcal: 20, isCustom: true },
    { id: 'o1', name: 'Magere kwark (per 100g)', kcal: 55 },
    { id: 'o2', name: 'Gekookt ei', kcal: 75 },
    { id: 'o3', name: 'Volkoren cracker (Wasa)', kcal: 35 },
  ],
  'Ochtend snack': [
    ...COMMON_DRINKS,
    { id: 'c_proteine_lepel', name: 'Proteine (Eetlepel)', kcal: 35, isCustom: true },
    { id: 'c_rijstkoek_lidl', name: 'Rijstenkoek (Lidl)', kcal: 30, isCustom: true },
    { id: 'c_volkoren_cracker_lidl', name: 'Volkoren Cracker (Lidl)', kcal: 35, isCustom: true },
    { id: 't1_1', name: 'Appel (met schil)', kcal: 80 },
  ],
  'Lunch': [
    ...COMMON_DRINKS,
    { id: 'c_tomatensoep_300', name: 'Zelfgemaakte tomatensoep (300 ml)', kcal: 90, isCustom: true },
    { id: 'c_pindakaas_lepel', name: 'Pindakaas (Eetlepel)', kcal: 95, isCustom: true },
    { id: 'l_b1', name: 'Volkoren boterham', kcal: 85 },
  ],
  'Middag snack': [
    ...COMMON_DRINKS,
    { id: 'c_proteine_lepel', name: 'Proteine (Eetlepel)', kcal: 35, isCustom: true },
    { id: 'c_rijstkoek_lidl', name: 'Rijstenkoek (Lidl)', kcal: 30, isCustom: true },
  ],
  'Diner': [
    ...COMMON_DRINKS,
    ...ALCOHOLIC_DRINKS,
    { id: 'c_zilvervlies_ongekookt', name: 'Zilvervliesrijst ongekookt (100 gr)', kcal: 350, isCustom: true },
    { id: 'c_zilvervlies_gekookt', name: 'Zilvervliesrijst gekookt (100 gr)', kcal: 135, isCustom: true },
    { id: 'd1', name: 'Nasi/Bami Groenten (500g)', kcal: 160 },
  ],
  'Avondsnack': [
    ...COMMON_DRINKS,
    ...ALCOHOLIC_DRINKS,
    { id: 'c_proteine_lepel', name: 'Proteine (Eetlepel)', kcal: 35, isCustom: true },
    { id: 'c_rijstkoek_lidl', name: 'Rijstenkoek (Lidl)', kcal: 30, isCustom: true },
    { id: 'a2', name: 'Blokje Pure Chocolade (85%)', kcal: 55 },
  ],
};

export const ACTIVITY_TYPES: ActivityType[] = [
  { id: 'c_water_spelen', name: 'Zwemmen/ spelen in water', met: 3.8, unit: 'minuten' },
  { id: 'wandelen_5', name: 'Wandelen (5 km per uur)', met: 3.5, unit: 'minuten' },
  { id: 'wandelen_tempo', name: 'Wandelen (stevig tempo)', met: 4.5, unit: 'minuten' },
  { id: 'hardlopen', name: 'Hardlopen (10 km/u)', met: 10.0, unit: 'minuten' },
  { id: 'fietsen', name: 'Fietsen (rustig)', met: 6.0, unit: 'minuten' },
  { id: 'zwemmen', name: 'Zwemmen (recreatief)', met: 6.0, unit: 'minuten' },
  { id: 'padellen', name: 'Padellen', met: 8.0, unit: 'minuten' },
  { id: 'krachttraining', name: 'Krachttraining / Fitness', met: 5.0, unit: 'minuten' },
];

export const DAILY_KCAL_INTAKE_GOAL = 1800;
export const KCAL_PER_KG_FAT = 7700;
