
import { MealOption, ActivityType, MealMoment, Language } from './types';

export const MEAL_MOMENTS: MealMoment[] = [
  'Ontbijt',
  'Ochtend Snack',
  'Lunch',
  'Middag Snack',
  'Diner',
  'Avond Snack'
];

export const PRODUCT_TRANSLATIONS: Record<Language, Record<string, string>> = {
  nl: {
    // Shared / Generic Drinks (75)
    d_water: 'Water (Plat/Bruis)', d_water_citroen: 'Water met Citroen', d_water_munt: 'Water met Munt', d_cola_zero: 'Cola Zero', d_pepsi_max: 'Pepsi Max', d_fanta_zero: 'Fanta Orange Zero', d_sprite_zero: 'Sprite Zero', d_icetea_green_zero: 'Ice Tea Green Zero', d_rivella: 'Rivella Original', d_spa_touch: 'Spa Touch Lemon', d_koffie: 'Koffie (Zwart)', d_espresso: 'Espresso', d_americano: 'Americano', d_thee_groen: 'Groene Thee', d_thee_zwart: 'Zwarte Thee', d_thee_kruiden: 'Kruidenthee', d_verse_munt: 'Verse Muntthee', d_gemberthee: 'Verse Gemberthee', d_melk_mager: 'Magere Melk', d_melk_half: 'Halfvolle Melk', d_melk_soja: 'Sojamelk (Ongezoet)', d_melk_amandel: 'Amandelmelk (Ongezoet)', d_melk_haver: 'Havermelk (Ongezoet)', d_eiwitshake_water: 'Eiwitshake (Water)', d_eiwitshake_melk: 'Eiwitshake (Melk)', d_bouillon: 'Bouillon', d_sinaasappelsap: 'Sinaasappelsap', d_appelsap: 'Appelsap', d_tomatensap: 'Tomatensap', d_limonade_zero: 'Limonade Zero', d_rooibos: 'Rooibos Thee', d_karnemelk: 'Karnemelk', d_kokoswater: 'Kokoswater', d_bietensap: 'Bietensap', d_grapefruitsap: 'Grapefruitsap', d_ijskoffie: 'IJskoffie (Zwart)', d_crystal_clear: 'Crystal Clear Lemon', d_optimel: 'Optimel Drink', d_ananassap: 'Ananassap', d_perensap: 'Perensap', d_wortelsap: 'Verse Wortelsap', d_eiwitwater: 'Eiwitwater', d_matcha: 'Matcha Latte (Amandel)', d_vlierbloesem: 'Vlierbloesem Drink Zero', d_chocomel_zero: 'Chocomel Zero', d_kefir: 'Kefir Naturel', d_komkommersap: 'Komkommersap', d_granaatappel: 'Granaatappelsap', d_aloe_vera: 'Aloë Vera Drink', d_ijsthee_perzik: 'IJsthee Perzik Zero', d_dr_pepper: 'Dr. Pepper Zero', d_ginger_beer: 'Ginger Beer (Suikervrij)', d_ranja: 'Ranja Fruitmix Zero', d_brandnetelthee: 'Verse Brandnetelthee', d_kamille: 'Kamille Thee', d_earl_grey: 'Earl Grey', d_cold_brew: 'Cold Brew Coffee', d_cranberrysap: 'Verse Cranberrysap', d_vitamin_water: 'Vitamin Water Zero', d_protein_smoothie: 'Protein Smoothie (Rood fruit)', d_erwtenmelk: 'Erwtenmelk (Ongezoet)', d_rijstmelk: 'Rijstmelk', d_speltmelk: 'Speltmelk', d_kasuwsap: 'Kasuwsap', d_bosvruchtensap: 'Bosvruchtensap', d_multivitaminesap: 'Multivitaminesap', d_yogi_tea: 'Yogi Tea', d_kombucha: 'Kombucha Original', d_bamboe_thee: 'Bamboe Thee', d_gerstewater: 'Gerstewater', d_miso: 'Miso Soep', d_salie_thee: 'Verse Salie Thee', d_lauwwarm_citroen: 'Lauwwarm Water Citroen', d_hibiscus: 'Hibiscus Thee', d_yerba_mate: 'Yerba Mate',
    // Alcohol (75)
    a_bier_pils: 'Bier (Pils)', a_bier_speciaal: 'Speciaalbier', a_bier_ipa: 'IPA Bier', a_bier_wit: 'Witbier', a_wijn_rood: 'Rode Wijn', a_wijn_wit_droog: 'Witte Wijn (Droog)', a_wijn_wit_zoet: 'Witte Wijn (Zoet)', a_wijn_rose: 'Rosé Wijn', a_prosecco: 'Prosecco / Champagne', a_gin_tonic: 'Gin Tonic', a_whiskey: 'Whiskey', a_rum_cola: 'Rum Cola', a_vodka_lemon: 'Vodka Lemon', a_aperol: 'Aperol Spritz', a_shotje: 'Shotje (Sterk)', a_mojito: 'Mojito', a_margarita: 'Margarita', a_martini: 'Martini', a_sangria: 'Sangria', a_tequila: 'Tequila', a_cognac: 'Cognac', a_baileys: 'Baileys', a_port: 'Port', a_sherry: 'Sherry', a_sake: 'Sake', a_cider: 'Cider', a_negroni: 'Negroni', a_moscow_mule: 'Moscow Mule', a_caipirinha: 'Caipirinha', a_espresso_martini: 'Espresso Martini', a_bier_vrij: 'Alcoholvrij Bier', a_radler_2: 'Radler 2.0%', a_radler_0: 'Radler 0.0%', a_hugo: 'Hugo', a_pina_colada: 'Pina Colada', a_old_fashioned: 'Old Fashioned', a_manhattan: 'Manhattan', a_cosmopolitan: 'Cosmopolitan', a_whiskey_sour: 'Whiskey Sour', a_long_island: 'Long Island Ice Tea', a_amaretto: 'Amaretto', a_limoncello: 'Limoncello', a_jager: 'Jagermeister', a_gin_pure: 'Gin (Pure)', a_vodka_pure: 'Vodka (Pure)', a_rum_pure: 'Rum (Pure)', a_pastis: 'Pastis', a_calvados: 'Calvados', a_grappa: 'Grappa', a_gedistilleerd: 'Gedistilleerd 40%', a_weizen: 'Weizenbier', a_dubbel: 'Dubbel Bier', a_tripel: 'Tripel Bier', a_stout: 'Stout Bier', a_dessertwijn: 'Dessertwijn', a_witte_port: 'Witte Port', a_vermout: 'Vermout', a_campari: 'Campari', a_grand_marnier: 'Grand Marnier', a_tia_maria: 'Tia Maria', a_sambuca: 'Sambuca', a_tequila_sunrise: 'Tequila Sunrise', a_white_russian: 'White Russian', a_black_russian: 'Black Russian', a_sex_beach: 'Sex on the Beach', a_dark_stormy: 'Dark and Stormy', a_bloody_mary: 'Bloody Mary', a_daiquiri: 'Daiquiri', a_tom_collins: 'Tom Collins', a_mai_tai: 'Mai Tai', a_bellini: 'Bellini', a_kir_royale: 'Kir Royale', a_mead: 'Mead (Mede)', a_pernod: 'Pernod', a_advocaat: 'Advocaat',
    // Breakfast (75)
    b_skyr: 'Skyr Natuur', b_griekse_yoghurt: 'Griekse Yoghurt (10%)', b_magere_kwark: 'Magere Kwark', b_havermout: 'Havermout (Water)', b_volkoren_brood: 'Volkoren Brood', b_ei_gekookt: 'Ei (Gekookt)', b_pindakaas_brood: 'Brood Pindakaas', b_roerei: 'Roerei', b_smoothie_groen: 'Groene Smoothie', b_brinta: 'Brinta met Melk', b_muesli: 'Muesli (Ongezoet)', b_cruesli: 'Cruesli (Chocolade)', b_banaan: 'Banaan', b_appel_kaneel: 'Appel met Kaneel', b_kwark_bessen: 'Kwark met Blauwe Bessen', b_omelet_spinazie: 'Omelet met Spinazie', b_gepocheerd_ei: 'Gepocheerd Ei', b_roggebrood: 'Roggebrood', b_beschuit: 'Beschuit', b_knackebrod: 'Knäckebröd (Volkoren)', b_huttenkase: 'Hüttenkäse', b_amandelpasta: 'Amandelpasta (op brood)', b_chia_pudding: 'Chia Pudding (Amandelmelk)', b_pannenkoek: 'Pannenkoek (Volkoren)', b_wentelteefje: 'Wentelteefje (Volkoren)', b_maiswafel: 'Maïswafel', b_speltbrood: 'Speltbrood', b_smoothie_bowl: 'Smoothie Bowl (Acaï)', b_overnight_oats: 'Overnight Oats', b_geroosterd_brood: 'Geroosterd Brood', b_rijstepap: 'Rijstepap', b_teff: 'Teff Ontbijt', b_eiwit_pannenkoeken: 'Eiwit-pannenkoeken', b_gebakken_ei: 'Gebakken Ei', b_ontbijtkoek_minder: 'Ontbijtkoek (Minder suiker)', b_vruchtenhagel: 'Vruchtenhagel (op brood)', b_hagelslag_puur: 'Hagelslag Puur (op brood)', b_jam: 'Jam (Halvajam)', b_honing_brood: 'Honing (op brood)', b_sojakwark: 'Sojakwark', b_aardbeien: 'Aardbeien', b_grapefruit: 'Grapefruit', b_avocado_toast: 'Avocado op Toast', b_kipfilet_beleg: 'Kipfilet (Beleg)', b_rookvlees_beleg: 'Rookvlees (Beleg)', b_kaas_20: '20+ Kaas (Beleg)', b_kaas_30: '30+ Kaas (Beleg)', b_kaas_48: '48+ Kaas (Beleg)', b_smeerkaas: 'Smeerkaas (Mager)', b_hummus_brood: 'Hummus (op brood)', b_appelstroop: 'Appelstroop', b_vlokken: 'Vlokken Melk', b_kokosbrood: 'Kokosbrood', b_cornflakes: 'Cornflakes', b_gepofte_tarwe: 'Gepofte Tarwe', b_bulgur_ontbijt: 'Bulgur Ontbijt', b_quinoa_pap: 'Quinoa Pap', b_pecannoten_b: 'Pecannoten (Gepeld)', b_walnoten_b: 'Walnoten (Gepeld)', b_lijnzaad: 'Lijnzaad (Gebroken)', b_hennepzaad: 'Hennepzaad', b_pompoenpitten_b: 'Pompoenpitten', b_zonnebloempitten_b: 'Zonnebloempitten', b_meloen: 'Meloen (Galia)', b_kiwi_b: 'Kiwi', b_mango_b: 'Mango', b_peer_b: 'Peer', b_sinaasappel_b: 'Sinaasappel', b_papaya_b: 'Papaya', b_kwark_noten_b: 'Kwark met Noten', b_granola_eiwit: 'Eiwitrijke Granola', b_tofu_scramble: 'Tofu Scramble', b_breakfast_burrito: 'Breakfast Burrito (Groente)', b_bagel_volkoren: 'Bagel (Volkoren)', b_muffin: 'Muffin (Havermout)',
    // Lunch (75)
    l_soep_tomaat: 'Tomatensoep', l_wrap_zalm: 'Wrap met Zalm', l_salade_caesar: 'Caesar Salade', l_tosti: 'Tosti Ham/Kaas', l_pokebowl_zalm: 'Poke Bowl Zalm', l_broodje_bal: 'Broodje Bal Gehakt', l_clubsandwich: 'Club Sandwich', l_erwtensoep: 'Erwtensoep (Snert)', l_salade_kip: 'Maaltijdsalade Kip', l_uitsmijter: 'Uitsmijter (3 eieren)', l_soep_groente: 'Groentesoep', l_salade_quinoa: 'Quinoa Salade', l_couscous_feta: 'Couscous met Feta', l_bol_gezond: 'Italiaanse Bol Gezond', l_krentenbol: 'Krentenbol', l_broodje_kroket: 'Broodje Kroket', l_broodje_frikandel: 'Broodje Frikandel', l_panini_pesto: 'Panini Kip Pesto', l_soep_linzen: 'Linzensoep', l_salade_nicoise: 'Nicoise Salade', l_tonijnsalade: 'Tonijnsalade', l_eiersalade: 'Eiersalade (Mager)', l_wrap_falafel: 'Falafel Wrap', l_pita_hummus: 'Pitabroodje Hummus', l_sushi_maki: 'Sushi (Maki 6 stuks)', l_kip_corne: 'Kip Corné', l_garnalencocktail: 'Garnalencocktail', l_rundvleessalade: 'Rundvleessalade', l_aardappelsalade: 'Aardappelsalade', l_soep_pompoen: 'Pompoensoep', l_soep_champignon: 'Champignonsoep', l_soep_mosterd: 'Mosterdsoep', l_stokbrood_kruidenboter: 'Stokbroodje Kruidenboter', l_wrap_kebab: 'Kebab Wrap', l_turks_brood: 'Turks Brood (Kwart)', l_salade_carpaccio: 'Carpaccio Salade', l_broodje_warm_vlees: 'Broodje Warm Vlees', l_surinaams_kip: 'Surinaamse Broodje Kip', l_bami_soep: 'Bami Soep', l_miso_ramen: 'Miso Ramen', l_salade_caprese: 'Caprese Salade', l_salade_grieks: 'Griekse Salade', l_pasta_pesto: 'Pasta Salade Pesto', l_salade_bulgur: 'Bulgur Salade', l_broodje_brie: 'Broodje Brie', l_broodje_rosbief: 'Broodje Rosbief', l_omelet_champignon: 'Omelet Champignon', l_knakworstjes: 'Knakworstjes (3 stuks)', l_bol_wit: 'Zachte Witte Bol', l_kaiserbroodje: 'Kaiserbroodje', l_taco_shells: 'Taco Shells (3 stuks)', l_burrito_vega: 'Burrito Vegetarisch', l_enchilada_kip: 'Enchilada Kip', l_quesadilla: 'Quesadilla Kaas', l_pannenkoek_ui: 'Lente-ui Pannenkoek', l_sashimi: 'Sashimi Mix', l_edamame_l: 'Edamame Bonen', l_soep_zuurkool: 'Zuurkoolsoep', l_soep_kip: 'Kippensoep', l_soep_uien: 'Franse Uiensoep', l_gazpacho: 'Gazpacho', l_soep_asperge: 'Aspergesoep', l_broodje_makreel: 'Broodje Makreel', l_broodje_haring: 'Broodje Haring', l_salade_forel: 'Gerookte Forel Salade', l_salade_waldorf: 'Waldorf Salade', l_pokebowl_tofu: 'Poke Bowl Tofu', l_roti_roll: 'Roti Roll', l_tosti_hawaii: 'Tosti Hawaii', l_knakworst_vega: 'Knakworst (Vegetarisch)', l_broodje_oude_kaas: 'Broodje Oude Kaas', l_pistolet_filet: 'Pistoletje Filet Americain', l_gevuld_ei_l: 'Gevuld Ei (2 stuks)', l_garnalenkroket: 'Garnalenkroket', l_bitterballen: 'Bitterballen (5 stuks)',
    // Diner (75)
    m_macaroni: 'Macaroni Bolognese', m_pizza_mar: 'Pizza Margherita', m_hutspot: 'Hutspot met klapstuk', m_zalmmoot: 'Zalmmoot', m_stamppot_boerenkool: 'Stamppot Boerenkool', m_lasagne: 'Lasagne Bolognese', m_sushi_box: 'Sushi Box', m_biefstuk_friet: 'Biefstuk met Friet', m_spaghetti_carb: 'Spaghetti Carbonara', m_risotto_pad: 'Risotto met Paddenstoelen', m_kip_tandoori: 'Kip Tandoori met Rijst', m_runderstoof: 'Runderstoofpot', m_varkenshaas: 'Varkenshaas Champignonsaus', m_kabeljauw_oven: 'Kabeljauw uit de oven', m_gevulde_paprika: 'Gevulde Paprika (Gehakt)', m_groene_curry: 'Thaise Groene Curry', m_nasi_goreng: 'Nasi Goreng met Ei', m_bami_goreng: 'Bami Goreng met Saté', m_moussaka: 'Moussaka', m_ravioli_ricotta: 'Ravioli Ricotta/Spinazie', m_hachee: 'Hachee', m_zuurkoolstamppot: 'Zuurkoolstamppot met Worst', m_andijviestamppot: 'Andijviestamppot met Spek', m_gado_gado: 'Gado Gado', m_pasta_pesto: 'Pasta Pesto met Kip', m_shoarma_pita: 'Shoarma met Pita', m_friet_mayo: 'Friet met Mayonaise', m_kipschnitzel: 'Kipschnitzel', m_wiener_schnitzel: 'Wiener Schnitzel', m_chili_carne: 'Chili con Carne', m_chili_sin_carne: 'Chili sin Carne', m_ratatouille: 'Ratatouille', m_paella: 'Paella', m_tortellini_bouillon: 'Tortellini in Bouillon', m_gnocchi: 'Gnocchi Tomatensaus', m_lamskotelet: 'Lamskoteletjes (2 stuks)', m_eendenborst: 'Eendenborst', m_tongfilet: 'Tongfilet Gebakken', m_forel_oven: 'Forel uit de oven', m_mosselen: 'Mosselen (Pan)', m_garnalen_wok: 'Garnalen uit de Wok', m_quiche_lorraine: 'Quiche Lorraine', m_zweedse_ballen: 'Zweedse Gehaktballen', m_goulash: 'Goulash', m_hertenbiefstuk: 'Hertenbiefstuk', m_kip_marengo: 'Kip Marengo', m_ossobuco: 'Ossobuco', m_varkensrollade: 'Varkensrollade', m_kalkoenfilet: 'Kalkoenfilet Gebakken', m_zwaardvis: 'Zwaardvissteak', m_inktvisringen: 'Inktvisringen', m_wieners_grill: 'Wieners van de grill', m_hotwings: 'Kipvleugels (Hotwings)', m_spareribs: 'Spareribs (Gegrild)', m_vega_burger: 'Vegetarische Burger', m_falafel_set: 'Falafel (5 stuks)', m_tempeh_ketjap: 'Tempeh Ketjap', m_tofu_roerbak: 'Tofu Roerbak', m_seitan_steaks: 'Seitan Steaks', m_spruitjes_spek: 'Spruitjes met Spekjes', m_asperges_ham_ei: 'Asperges met Ham/Ei', m_courgette_vega: 'Gevulde Courgette (Vega)', m_enchiladas: 'Mexicaanse Enchiladas', m_tagliatelle_truffel: 'Tagliatelle Truffel', m_penne_arrabiata: 'Penne Arrabiata', m_fusilli_tonijn: 'Fusilli met Tonijn', m_couscous_lam: 'Couscous met Lamsvlees', m_siu_mai: 'Kip Siu Mai (8 stuks)', m_babi_pangang: 'Babi Pangang', m_foe_yong_hai: 'Foe Yong Hai', m_tjap_tjoy: 'Tjap Tjoy met Kip', m_rijsttafel: 'Indische Rijsttafel', m_boeuf_bourg: 'Boeuf Bourguignon', m_coq_au_vin: 'Coq au Vin', m_cassoulet: 'Cassoulet',
    // Snacks & Fruit (60 Snacks + Fruits)
    s_amandelen: 'Amandelen', s_rijstwafel_hummus: 'Rijstwafel Hummus', s_pure_choco: 'Pure Chocolade (85%)', s_snoeptomaatjes: 'Snoeptomaatjes', s_komkommer: 'Komkommer', s_cracker_huttenkase: 'Cracker Hüttenkäse', s_olijven_g: 'Olijven (Groen)', s_olijven_z: 'Olijven (Zwart)', s_gekookt_ei: 'Gekookt Ei', s_walnoten: 'Walnoten', s_kaas_48_b: 'Blokje Kaas (48+)', s_kaas_30_b: 'Blokje Kaas (30+)', s_pindas: "Pinda's (Gezouten)", s_augurk: 'Augurk', s_zoute_stengels: 'Zoute Stengels', s_japanse_mix: 'Japanse Mix', s_borrelnootjes: 'Borrelnootjes', s_chips_nat: 'Chips (Naturel)', s_chips_pap: 'Chips (Paprika)', s_tortilla_chips: 'Tortilla Chips', s_pretzels: 'Pretzels', s_eierkoek: 'Eierkoek', s_ontbijtkoek_s: 'Ontbijtkoek', s_speculaasje: 'Speculaasje', s_mariakaakje: 'Mariakaakje', s_stroopwafel: 'Stroopwafel', s_gevulde_koek: 'Gevulde Koek', s_oat_cookies: 'Oat Cookies', s_rijstwafel_choco: 'Rijstwafel Choco', s_protein_bar: 'Protein Bar', s_bifi: 'Bifi Worstje', s_babybel: 'Mini Babybel', s_dadelballetje: 'Dadelballetje', s_kikkererwten_geroosterd: 'Geroosterde Kikkererwten', s_gedroogde_mango: 'Gedroogde Mango', s_gedroogde_abrikozen: 'Gedroogde Abrikozen', s_popcorn_zout: 'Popcorn (Zout)', s_popcorn_zoet: 'Popcorn (Zoet)', s_rijstwafel_kaas: 'Rijstwafel (Kaas)', s_paprika_reepjes: 'Paprika Reepjes', s_bleekselderij: 'Bleekselderij', s_radijsjes: 'Radijsjes', s_blokje_ham: 'Blokje Achterham', s_kipfilet_rolletje: 'Rolletje Kipfilet', s_sojabonen: 'Sojabonen (Edamame)', s_kwark_honing_s: 'Kwark met Honing', s_griekse_yoghurt_snack: 'Griekse Yoghurt', s_rozijnen_s: 'Rozijnen', s_pistachenoten_s: 'Pistachenoten', s_pecannoten_snack: 'Pecannoten', s_hazelnoten_snack: 'Hazelnoten', s_paranoten: 'Paranoten', s_macadamia: 'Macadamia noten', s_cashewnoten_snack: 'Cashewnoten', s_pompoenpitten_snack: 'Pompoenpitten', s_zonnebloempitten_snack: 'Zonnebloempitten', s_rijstwafel_appel: 'Rijstwafel Appel/Kaneel', s_cracker_pindakaas: 'Cracker Pindakaas', s_ontbijtkoek_zero: 'Ontbijtkoek Zero', s_snack_wortel: 'Snackworteltjes',
    f_appel: 'Appel', f_banaan: 'Banaan', f_watermeloen: 'Watermeloen', f_druiven: 'Druiven', f_blauwe_bessen: 'Blauwe Bessen', f_peer: 'Peer', f_sinaasappel: 'Sinaasappel', f_kiwi: 'Kiwi', f_mango: 'Mango', f_aardbeien: 'Aardbeien', f_frambozen: 'Frambozen', f_bramen: 'Bramen', f_ananas: 'Ananas', f_perzik: 'Perzik', f_nectarine: 'Nectarine', f_pruim: 'Pruim', f_abrikoos: 'Abrikoos', f_kersen: 'Kersen', f_cantaloupe: 'Meloen (Cantaloupe)', f_papaya: 'Papaya', f_passievrucht: 'Passievrucht', f_vijgen: 'Vijgen (Vers)', f_dadels_gedroogd: 'Dadels (Gedroogd)', f_rozijnen_f: 'Rozijnen'
  },
  en: {}, es: {}, de: {}, pt: {}, zh: {}, ja: {}, ko: {}, hi: {}, ar: {}
};

const NON_ALC_DRINKS: MealOption[] = [
  { id: 'd_water', name: 'Water (Plat/Bruis)', kcal: 0, isDrink: true, unitName: '250 ML' },
  { id: 'd_water_citroen', name: 'Water met Citroen', kcal: 2, isDrink: true, unitName: '250 ML' },
  { id: 'd_water_munt', name: 'Water met Munt', kcal: 2, isDrink: true, unitName: '250 ML' },
  { id: 'd_cola_zero', name: 'Cola Zero', kcal: 0, isDrink: true, unitName: '250 ML' },
  { id: 'd_pepsi_max', name: 'Pepsi Max', kcal: 0, isDrink: true, unitName: '250 ML' },
  { id: 'd_fanta_zero', name: 'Fanta Orange Zero', kcal: 10, isDrink: true, unitName: '250 ML' },
  { id: 'd_sprite_zero', name: 'Sprite Zero', kcal: 5, isDrink: true, unitName: '250 ML' },
  { id: 'd_icetea_green_zero', name: 'Ice Tea Green Zero', kcal: 5, isDrink: true, unitName: '250 ML' },
  { id: 'd_rivella', name: 'Rivella Original', kcal: 13, isDrink: true, unitName: '250 ML' },
  { id: 'd_spa_touch', name: 'Spa Touch Lemon', kcal: 0, isDrink: true, unitName: '250 ML' },
  { id: 'd_koffie', name: 'Koffie (Zwart)', kcal: 2, isDrink: true, unitName: '200 ML' },
  { id: 'd_espresso', name: 'Espresso', kcal: 2, isDrink: true, unitName: '35 ML' },
  { id: 'd_americano', name: 'Americano', kcal: 2, isDrink: true, unitName: '200 ML' },
  { id: 'd_thee_groen', name: 'Groene Thee', kcal: 1, isDrink: true, unitName: '200 ML' },
  { id: 'd_thee_zwart', name: 'Zwarte Thee', kcal: 1, isDrink: true, unitName: '200 ML' },
  { id: 'd_thee_kruiden', name: 'Kruidenthee', kcal: 1, isDrink: true, unitName: '200 ML' },
  { id: 'd_verse_munt', name: 'Verse Muntthee', kcal: 5, isDrink: true, unitName: '250 ML' },
  { id: 'd_gemberthee', name: 'Verse Gemberthee', kcal: 5, isDrink: true, unitName: '250 ML' },
  { id: 'd_melk_mager', name: 'Magere Melk', kcal: 85, isDrink: true, unitName: '250 ML' },
  { id: 'd_melk_half', name: 'Halfvolle Melk', kcal: 115, isDrink: true, unitName: '250 ML' },
  { id: 'd_melk_soja', name: 'Sojamelk (Ongezoet)', kcal: 80, isDrink: true, unitName: '250 ML' },
  { id: 'd_melk_amandel', name: 'Amandelmelk (Ongezoet)', kcal: 35, isDrink: true, unitName: '250 ML' },
  { id: 'd_melk_haver', name: 'Havermelk (Ongezoet)', kcal: 110, isDrink: true, unitName: '250 ML' },
  { id: 'd_eiwitshake_water', name: 'Eiwitshake (Water)', kcal: 110, isDrink: true, unitName: '300 ML' },
  { id: 'd_eiwitshake_melk', name: 'Eiwitshake (Melk)', kcal: 210, isDrink: true, unitName: '300 ML' },
  { id: 'd_bouillon', name: 'Bouillon', kcal: 10, isDrink: true, unitName: '250 ML' },
  { id: 'd_sinaasappelsap', name: 'Sinaasappelsap', kcal: 115, isDrink: true, unitName: '250 ML' },
  { id: 'd_appelsap', name: 'Appelsap', kcal: 110, isDrink: true, unitName: '250 ML' },
  { id: 'd_tomatensap', name: 'Tomatensap', kcal: 45, isDrink: true, unitName: '250 ML' },
  { id: 'd_limonade_zero', name: 'Limonade Zero', kcal: 2, isDrink: true, unitName: '250 ML' },
  { id: 'd_rooibos', name: 'Rooibos Thee', kcal: 1, isDrink: true, unitName: '200 ML' },
  { id: 'd_karnemelk', name: 'Karnemelk', kcal: 93, isDrink: true, unitName: '250 ML' },
  { id: 'd_kokoswater', name: 'Kokoswater', kcal: 48, isDrink: true, unitName: '250 ML' },
  { id: 'd_bietensap', name: 'Bietensap', kcal: 105, isDrink: true, unitName: '250 ML' },
  { id: 'd_grapefruitsap', name: 'Grapefruitsap', kcal: 95, isDrink: true, unitName: '250 ML' },
  { id: 'd_ijskoffie', name: 'IJskoffie (Zwart)', kcal: 5, isDrink: true, unitName: '250 ML' },
  { id: 'd_crystal_clear', name: 'Crystal Clear Lemon', kcal: 2, isDrink: true, unitName: '250 ML' },
  { id: 'd_optimel', name: 'Optimel Drink', kcal: 70, isDrink: true, unitName: '250 ML' },
  { id: 'd_ananassap', name: 'Ananassap', kcal: 125, isDrink: true, unitName: '250 ML' },
  { id: 'd_perensap', name: 'Perensap', kcal: 118, isDrink: true, unitName: '250 ML' },
  { id: 'd_wortelsap', name: 'Verse Wortelsap', kcal: 85, isDrink: true, unitName: '250 ML' },
  { id: 'd_eiwitwater', name: 'Eiwitwater', kcal: 60, isDrink: true, unitName: '500 ML' },
  { id: 'd_matcha', name: 'Matcha Latte (Amandel)', kcal: 45, isDrink: true, unitName: '250 ML' },
  { id: 'd_vlierbloesem', name: 'Vlierbloesem Drink Zero', kcal: 4, isDrink: true, unitName: '250 ML' },
  { id: 'd_chocomel_zero', name: 'Chocomel Zero', kcal: 118, isDrink: true, unitName: '250 ML' },
  { id: 'd_kefir', name: 'Kefir Naturel', kcal: 125, isDrink: true, unitName: '250 ML' },
  { id: 'd_komkommersap', name: 'Komkommersap', kcal: 35, isDrink: true, unitName: '250 ML' },
  { id: 'd_granaatappel', name: 'Granaatappelsap', kcal: 160, isDrink: true, unitName: '250 ML' },
  { id: 'd_aloe_vera', name: 'Aloë Vera Drink', kcal: 90, isDrink: true, unitName: '250 ML' },
  { id: 'd_ijsthee_perzik', name: 'IJsthee Perzik Zero', kcal: 4, isDrink: true, unitName: '250 ML' },
  { id: 'd_dr_pepper', name: 'Dr. Pepper Zero', kcal: 0, isDrink: true, unitName: '250 ML' },
  { id: 'd_ginger_beer', name: 'Ginger Beer (Suikervrij)', kcal: 5, isDrink: true, unitName: '250 ML' },
  { id: 'd_ranja', name: 'Ranja Fruitmix Zero', kcal: 3, isDrink: true, unitName: '250 ML' },
  { id: 'd_brandnetelthee', name: 'Verse Brandnetelthee', kcal: 2, isDrink: true, unitName: '250 ML' },
  { id: 'd_kamille', name: 'Kamille Thee', kcal: 1, isDrink: true, unitName: '200 ML' },
  { id: 'd_earl_grey', name: 'Earl Grey', kcal: 1, isDrink: true, unitName: '200 ML' },
  { id: 'd_cold_brew', name: 'Cold Brew Coffee', kcal: 3, isDrink: true, unitName: '250 ML' },
  { id: 'd_cranberrysap', name: 'Verse Cranberrysap', kcal: 110, isDrink: true, unitName: '250 ML' },
  { id: 'd_vitamin_water', name: 'Vitamin Water Zero', kcal: 0, isDrink: true, unitName: '500 ML' },
  { id: 'd_protein_smoothie', name: 'Protein Smoothie (Rood fruit)', kcal: 180, isDrink: true, unitName: '250 ML' },
  { id: 'd_erwtenmelk', name: 'Erwtenmelk (Ongezoet)', kcal: 105, isDrink: true, unitName: '250 ML' },
  { id: 'd_rijstmelk', name: 'Rijstmelk', kcal: 120, isDrink: true, unitName: '250 ML' },
  { id: 'd_speltmelk', name: 'Speltmelk', kcal: 115, isDrink: true, unitName: '250 ML' },
  { id: 'd_kasuwsap', name: 'Kasuwsap', kcal: 100, isDrink: true, unitName: '250 ML' },
  { id: 'd_bosvruchtensap', name: 'Bosvruchtensap', kcal: 130, isDrink: true, unitName: '250 ML' },
  { id: 'd_multivitaminesap', name: 'Multivitaminesap', kcal: 115, isDrink: true, unitName: '250 ML' },
  { id: 'd_yogi_tea', name: 'Yogi Tea', kcal: 2, isDrink: true, unitName: '200 ML' },
  { id: 'd_kombucha', name: 'Kombucha Original', kcal: 35, isDrink: true, unitName: '250 ML' },
  { id: 'd_bamboe_thee', name: 'Bamboe Thee', kcal: 1, isDrink: true, unitName: '200 ML' },
  { id: 'd_gerstewater', name: 'Gerstewater', kcal: 45, isDrink: true, unitName: '250 ML' },
  { id: 'd_miso', name: 'Miso Soep', kcal: 35, isDrink: true, unitName: '200 ML' },
  { id: 'd_salie_thee', name: 'Verse Salie Thee', kcal: 2, isDrink: true, unitName: '200 ML' },
  { id: 'd_lauwwarm_citroen', name: 'Lauwwarm Water Citroen', kcal: 3, isDrink: true, unitName: '250 ML' },
  { id: 'd_hibiscus', name: 'Hibiscus Thee', kcal: 2, isDrink: true, unitName: '200 ML' },
  { id: 'd_yerba_mate', name: 'Yerba Mate', kcal: 2, isDrink: true, unitName: '250 ML' },
];

const ALCOHOL_DRINKS: MealOption[] = [
  { id: 'a_bier_pils', name: 'Bier (Pils)', kcal: 135, isDrink: true, isAlcohol: true, unitName: '300 ML' },
  { id: 'a_bier_speciaal', name: 'Speciaalbier', kcal: 210, isDrink: true, isAlcohol: true, unitName: '330 ML' },
  { id: 'a_bier_ipa', name: 'IPA Bier', kcal: 180, isDrink: true, isAlcohol: true, unitName: '330 ML' },
  { id: 'a_bier_wit', name: 'Witbier', kcal: 150, isDrink: true, isAlcohol: true, unitName: '300 ML' },
  { id: 'a_wijn_rood', name: 'Rode Wijn', kcal: 125, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_wijn_wit_droog', name: 'Witte Wijn (Droog)', kcal: 120, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_wijn_wit_zoet', name: 'Witte Wijn (Zoet)', kcal: 150, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_wijn_rose', name: 'Rosé Wijn', kcal: 115, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_prosecco', name: 'Prosecco / Champagne', kcal: 110, isDrink: true, isAlcohol: true, unitName: '125 ML' },
  { id: 'a_gin_tonic', name: 'Gin Tonic', kcal: 175, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_whiskey', name: 'Whiskey', kcal: 85, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_rum_cola', name: 'Rum Cola', kcal: 180, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_vodka_lemon', name: 'Vodka Lemon', kcal: 165, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_aperol', name: 'Aperol Spritz', kcal: 140, isDrink: true, isAlcohol: true, unitName: '200 ML' },
  { id: 'a_shotje', name: 'Shotje (Sterk)', kcal: 90, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_mojito', name: 'Mojito', kcal: 160, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_margarita', name: 'Margarita', kcal: 140, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_martini', name: 'Martini', kcal: 120, isDrink: true, isAlcohol: true, unitName: '100 ML' },
  { id: 'a_sangria', name: 'Sangria', kcal: 175, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_tequila', name: 'Tequila', kcal: 80, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_cognac', name: 'Cognac', kcal: 85, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_baileys', name: 'Baileys', kcal: 160, isDrink: true, isAlcohol: true, unitName: '50 ML' },
  { id: 'a_port', name: 'Port', kcal: 120, isDrink: true, isAlcohol: true, unitName: '75 ML' },
  { id: 'a_sherry', name: 'Sherry', kcal: 95, isDrink: true, isAlcohol: true, unitName: '75 ML' },
  { id: 'a_sake', name: 'Sake', kcal: 130, isDrink: true, isAlcohol: true, unitName: '100 ML' },
  { id: 'a_cider', name: 'Cider', kcal: 150, isDrink: true, isAlcohol: true, unitName: '330 ML' },
  { id: 'a_negroni', name: 'Negroni', kcal: 190, isDrink: true, isAlcohol: true, unitName: '100 ML' },
  { id: 'a_moscow_mule', name: 'Moscow Mule', kcal: 180, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_caipirinha', name: 'Caipirinha', kcal: 170, isDrink: true, isAlcohol: true, unitName: '200 ML' },
  { id: 'a_espresso_martini', name: 'Espresso Martini', kcal: 160, isDrink: true, isAlcohol: true, unitName: '125 ML' },
  { id: 'a_bier_vrij', name: 'Alcoholvrij Bier', kcal: 65, isDrink: true, isAlcohol: false, unitName: '300 ML' },
  { id: 'a_radler_2', name: 'Radler 2.0%', kcal: 130, isDrink: true, isAlcohol: true, unitName: '300 ML' },
  { id: 'a_radler_0', name: 'Radler 0.0%', kcal: 95, isDrink: true, isAlcohol: false, unitName: '300 ML' },
  { id: 'a_hugo', name: 'Hugo', kcal: 135, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_pina_colada', name: 'Pina Colada', kcal: 350, isDrink: true, isAlcohol: true, unitName: '200 ML' },
  { id: 'a_old_fashioned', name: 'Old Fashioned', kcal: 160, isDrink: true, isAlcohol: true, unitName: '100 ML' },
  { id: 'a_manhattan', name: 'Manhattan', kcal: 150, isDrink: true, isAlcohol: true, unitName: '100 ML' },
  { id: 'a_cosmopolitan', name: 'Cosmopolitan', kcal: 150, isDrink: true, isAlcohol: true, unitName: '125 ML' },
  { id: 'a_whiskey_sour', name: 'Whiskey Sour', kcal: 165, isDrink: true, isAlcohol: true, unitName: '125 ML' },
  { id: 'a_long_island', name: 'Long Island Ice Tea', kcal: 280, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_amaretto', name: 'Amaretto', kcal: 110, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_limoncello', name: 'Limoncello', kcal: 105, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_jager', name: 'Jagermeister', kcal: 100, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_gin_pure', name: 'Gin (Pure)', kcal: 85, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_vodka_pure', name: 'Vodka (Pure)', kcal: 80, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_rum_pure', name: 'Rum (Pure)', kcal: 85, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_pastis', name: 'Pastis', kcal: 100, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_calvados', name: 'Calvados', kcal: 85, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_grappa', name: 'Grappa', kcal: 85, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_gedistilleerd', name: 'Gedistilleerd 40%', kcal: 85, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_weizen', name: 'Weizenbier', kcal: 145, isDrink: true, isAlcohol: true, unitName: '300 ML' },
  { id: 'a_dubbel', name: 'Dubbel Bier', kcal: 220, isDrink: true, isAlcohol: true, unitName: '330 ML' },
  { id: 'a_tripel', name: 'Tripel Bier', kcal: 250, isDrink: true, isAlcohol: true, unitName: '330 ML' },
  { id: 'a_stout', name: 'Stout Bier', kcal: 160, isDrink: true, isAlcohol: true, unitName: '300 ML' },
  { id: 'a_dessertwijn', name: 'Dessertwijn', kcal: 160, isDrink: true, isAlcohol: true, unitName: '100 ML' },
  { id: 'a_witte_port', name: 'Witte Port', kcal: 115, isDrink: true, isAlcohol: true, unitName: '75 ML' },
  { id: 'a_vermout', name: 'Vermout', kcal: 120, isDrink: true, isAlcohol: true, unitName: '100 ML' },
  { id: 'a_campari', name: 'Campari', kcal: 90, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_grand_marnier', name: 'Grand Marnier', kcal: 125, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_tia_maria', name: 'Tia Maria', kcal: 115, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_sambuca', name: 'Sambuca', kcal: 120, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_tequila_sunrise', name: 'Tequila Sunrise', kcal: 200, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_white_russian', name: 'White Russian', kcal: 240, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_black_russian', name: 'Black Russian', kcal: 190, isDrink: true, isAlcohol: true, unitName: '125 ML' },
  { id: 'a_sex_beach', name: 'Sex on the Beach', kcal: 185, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_dark_stormy', name: 'Dark and Stormy', kcal: 170, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_bloody_mary', name: 'Bloody Mary', kcal: 125, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_daiquiri', name: 'Daiquiri', kcal: 140, isDrink: true, isAlcohol: true, unitName: '100 ML' },
  { id: 'a_tom_collins', name: 'Tom Collins', kcal: 160, isDrink: true, isAlcohol: true, unitName: '250 ML' },
  { id: 'a_mai_tai', name: 'Mai Tai', kcal: 260, isDrink: true, isAlcohol: true, unitName: '200 ML' },
  { id: 'a_bellini', name: 'Bellini', kcal: 120, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_kir_royale', name: 'Kir Royale', kcal: 130, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_mead', name: 'Mead (Mede)', kcal: 150, isDrink: true, isAlcohol: true, unitName: '150 ML' },
  { id: 'a_pernod', name: 'Pernod', kcal: 100, isDrink: true, isAlcohol: true, unitName: '35 ML' },
  { id: 'a_advocaat', name: 'Advocaat', kcal: 130, isDrink: true, isAlcohol: true, unitName: '50 ML' },
];

const BREAKFAST_LIST: MealOption[] = [
  { id: 'b_skyr', name: 'Skyr Natuur', kcal: 95, unitName: '150 G' },
  { id: 'b_griekse_yoghurt', name: 'Griekse Yoghurt (10%)', kcal: 180, unitName: '150 G' },
  { id: 'b_magere_kwark', name: 'Magere Kwark', kcal: 140, unitName: '250 G' },
  { id: 'b_havermout', name: 'Havermout (Water)', kcal: 130, unitName: '200 G' },
  { id: 'b_volkoren_brood', name: 'Volkoren Brood', kcal: 80, unitName: '35 G' },
  { id: 'b_ei_gekookt', name: 'Ei (Gekookt)', kcal: 75, unitName: '55 G' },
  { id: 'b_pindakaas_brood', name: 'Pindakaas (op brood)', kcal: 180, unitName: '50 G' },
  { id: 'b_roerei', name: 'Roerei', kcal: 190, unitName: '120 G' },
  { id: 'b_smoothie_groen', name: 'Groene Smoothie', kcal: 140, unitName: '250 ML' },
  { id: 'b_brinta', name: 'Brinta met Melk', kcal: 210, unitName: '250 ML' },
  { id: 'b_muesli', name: 'Muesli (Ongezoet)', kcal: 175, unitName: '50 G' },
  { id: 'b_cruesli', name: 'Cruesli (Chocolade)', kcal: 225, unitName: '50 G' },
  { id: 'b_banaan', name: 'Banaan', kcal: 105, unitName: '120 G' },
  { id: 'b_appel_kaneel', name: 'Appel met Kaneel', kcal: 65, unitName: '150 G' },
  { id: 'b_kwark_bessen', name: 'Kwark met Blauwe Bessen', kcal: 185, unitName: '250 G' },
  { id: 'b_omelet_spinazie', name: 'Omelet met Spinazie', kcal: 210, unitName: '150 G' },
  { id: 'b_gepocheerd_ei', name: 'Gepocheerd Ei', kcal: 75, unitName: '55 G' },
  { id: 'b_roggebrood', name: 'Roggebrood', kcal: 95, unitName: '50 G' },
  { id: 'b_beschuit', name: 'Beschuit (Vierkant)', kcal: 40, unitName: '20 G' },
  { id: 'b_knackebrod', name: 'Knäckebröd (Volkoren)', kcal: 35, unitName: '15 G' },
  { id: 'b_huttenkase', name: 'Hüttenkäse', kcal: 150, unitName: '150 G' },
  { id: 'b_amandelpasta', name: 'Amandelpasta (op brood)', kcal: 190, unitName: '30 G' },
  { id: 'b_chia_pudding', name: 'Chia Pudding (Amandelmelk)', kcal: 160, unitName: '200 G' },
  { id: 'b_pannenkoek', name: 'Pannenkoek (Volkoren)', kcal: 150, unitName: '100 G' },
  { id: 'b_wentelteefje', name: 'Wentelteefje (Volkoren)', kcal: 185, unitName: '100 G' },
  { id: 'b_maiswafel', name: 'Maïswafel', kcal: 30, unitName: '10 G' },
  { id: 'b_speltbrood', name: 'Speltbrood', kcal: 85, unitName: '35 G' },
  { id: 'b_smoothie_bowl', name: 'Smoothie Bowl (Acaï)', kcal: 280, unitName: '300 G' },
  { id: 'b_overnight_oats', name: 'Overnight Oats', kcal: 250, unitName: '250 G' },
  { id: 'b_geroosterd_brood', name: 'Geroosterd Brood', kcal: 80, unitName: '35 G' },
  { id: 'b_rijstepap', name: 'Rijstepap', kcal: 180, unitName: '200 G' },
  { id: 'b_teff', name: 'Teff Ontbijt', kcal: 190, unitName: '250 ML' },
  { id: 'b_eiwit_pannenkoeken', name: 'Eiwit-pannenkoeken', kcal: 220, unitName: '150 G' },
  { id: 'b_gebakken_ei', name: 'Gebakken Ei', kcal: 110, unitName: '55 G' },
  { id: 'b_ontbijtkoek_minder', name: 'Ontbijtkoek (Minder suiker)', kcal: 70, unitName: '30 G' },
  { id: 'b_vruchtenhagel', name: 'Vruchtenhagel (op brood)', kcal: 60, unitName: '15 G' },
  { id: 'b_hagelslag_puur', name: 'Hagelslag Puur (op brood)', kcal: 80, unitName: '15 G' },
  { id: 'b_jam', name: 'Jam (Halvajam)', kcal: 30, unitName: '15 G' },
  { id: 'b_honing_brood', name: 'Honing (op brood)', kcal: 65, unitName: '20 G' },
  { id: 'b_sojakwark', name: 'Sojakwark', kcal: 110, unitName: '150 G' },
  { id: 'b_aardbeien', name: 'Aardbeien', kcal: 45, unitName: '150 G' },
  { id: 'b_grapefruit', name: 'Grapefruit', kcal: 50, unitName: '150 G' },
  { id: 'b_avocado_toast', name: 'Avocado op Toast', kcal: 280, unitName: '150 G' },
  { id: 'b_kipfilet_beleg', name: 'Kipfilet (Beleg)', kcal: 15, unitName: '15 G' },
  { id: 'b_rookvlees_beleg', name: 'Rookvlees (Beleg)', kcal: 15, unitName: '15 G' },
  { id: 'b_kaas_20', name: '20+ Kaas (Beleg)', kcal: 50, unitName: '20 G' },
  { id: 'b_kaas_30', name: '30+ Kaas (Beleg)', kcal: 60, unitName: '20 G' },
  { id: 'b_kaas_48', name: '48+ Kaas (Beleg)', kcal: 80, unitName: '20 G' },
  { id: 'b_smeerkaas', name: 'Smeerkaas (Mager)', kcal: 35, unitName: '20 G' },
  { id: 'b_hummus_brood', name: 'Hummus (op brood)', kcal: 50, unitName: '30 G' },
  { id: 'b_appelstroop', name: 'Appelstroop', kcal: 45, unitName: '15 G' },
  { id: 'b_vlokken', name: 'Vlokken Melk', kcal: 75, unitName: '15 G' },
  { id: 'b_kokosbrood', name: 'Kokosbrood', kcal: 85, unitName: '20 G' },
  { id: 'b_cornflakes', name: 'Cornflakes', kcal: 110, unitName: '30 G' },
  { id: 'b_gepofte_tarwe', name: 'Gepofte Tarwe', kcal: 105, unitName: '30 G' },
  { id: 'b_bulgur_ontbijt', name: 'Bulgur Ontbijt', kcal: 160, unitName: '200 G' },
  { id: 'b_quinoa_pap', name: 'Quinoa Pap', kcal: 180, unitName: '200 G' },
  { id: 'b_pecannoten_b', name: 'Pecannoten (Gepeld)', kcal: 175, unitName: '25 G' },
  { id: 'b_walnoten_b', name: 'Walnoten (Gepeld)', kcal: 170, unitName: '25 G' },
  { id: 'b_lijnzaad', name: 'Lijnzaad (Gebroken)', kcal: 75, unitName: '15 G' },
  { id: 'b_hennepzaad', name: 'Hennepzaad', kcal: 85, unitName: '15 G' },
  { id: 'b_pompoenpitten_b', name: 'Pompoenpitten', kcal: 90, unitName: '15 G' },
  { id: 'b_zonnebloempitten_b', name: 'Zonnebloempitten', kcal: 85, unitName: '15 G' },
  { id: 'b_meloen', name: 'Meloen (Galia)', kcal: 60, unitName: '200 G' },
  { id: 'b_kiwi_b', name: 'Kiwi', kcal: 40, unitName: '75 G' },
  { id: 'b_mango_b', name: 'Mango', kcal: 95, unitName: '150 G' },
  { id: 'b_peer_b', name: 'Peer', kcal: 75, unitName: '150 G' },
  { id: 'b_sinaasappel_b', name: 'Sinaasappel', kcal: 65, unitName: '150 G' },
  { id: 'b_papaya_b', name: 'Papaya', kcal: 60, unitName: '150 G' },
  { id: 'b_kwark_noten_b', name: 'Kwark met Noten', kcal: 260, unitName: '250 G' },
  { id: 'b_granola_eiwit', name: 'Eiwitrijke Granola', kcal: 210, unitName: '50 G' },
  { id: 'b_tofu_scramble', name: 'Tofu Scramble', kcal: 160, unitName: '150 G' },
  { id: 'b_breakfast_burrito', name: 'Breakfast Burrito (Groente)', kcal: 350, unitName: '200 G' },
  { id: 'b_bagel_volkoren', name: 'Bagel (Volkoren)', kcal: 240, unitName: '85 G' },
  { id: 'b_muffin', name: 'Muffin (Havermout)', kcal: 180, unitName: '60 G' },
];

const LUNCH_LIST: MealOption[] = [
  { id: 'l_soep_tomaat', name: 'Tomatensoep', kcal: 80, unitName: '250 ML' },
  { id: 'l_wrap_zalm', name: 'Wrap met Zalm', kcal: 320, unitName: '150 G' },
  { id: 'l_salade_caesar', name: 'Caesar Salade', kcal: 450, unitName: '350 G' },
  { id: 'l_tosti', name: 'Tosti Ham/Kaas', kcal: 260, unitName: '110 G' },
  { id: 'l_pokebowl_zalm', name: 'Poke Bowl Zalm', kcal: 550, unitName: '400 G' },
  { id: 'l_broodje_bal', name: 'Broodje Bal Gehakt', kcal: 520, unitName: '250 G' },
  { id: 'l_clubsandwich', name: 'Club Sandwich', kcal: 580, unitName: '300 G' },
  { id: 'l_erwtensoep', name: 'Erwtensoep (Snert)', kcal: 250, unitName: '250 ML' },
  { id: 'l_salade_kip', name: 'Maaltijdsalade Kip', kcal: 380, unitName: '350 G' },
  { id: 'l_uitsmijter', name: 'Uitsmijter (3 eieren)', kcal: 480, unitName: '250 G' },
  { id: 'l_soep_groente', name: 'Groentesoep', kcal: 65, unitName: '250 ML' },
  { id: 'l_salade_quinoa', name: 'Quinoa Salade', kcal: 320, unitName: '250 G' },
  { id: 'l_couscous_feta', name: 'Couscous met Feta', kcal: 350, unitName: '250 G' },
  { id: 'l_bol_gezond', name: 'Italiaanse Bol Gezond', kcal: 420, unitName: '200 G' },
  { id: 'l_krentenbol', name: 'Krentenbol', kcal: 150, unitName: '50 G' },
  { id: 'l_broodje_kroket', name: 'Broodje Kroket', kcal: 350, unitName: '150 G' },
  { id: 'l_broodje_frikandel', name: 'Broodje Frikandel', kcal: 320, unitName: '150 G' },
  { id: 'l_panini_pesto', name: 'Panini Kip Pesto', kcal: 480, unitName: '200 G' },
  { id: 'l_soep_linzen', name: 'Linzensoep', kcal: 180, unitName: '250 ML' },
  { id: 'l_salade_nicoise', name: 'Nicoise Salade', kcal: 340, unitName: '300 G' },
  { id: 'l_tonijnsalade', name: 'Tonijnsalade (Huisgemaakt)', kcal: 220, unitName: '100 G' },
  { id: 'l_eiersalade', name: 'Eiersalade (Mager)', kcal: 160, unitName: '100 G' },
  { id: 'l_wrap_falafel', name: 'Falafel Wrap', kcal: 410, unitName: '200 G' },
  { id: 'l_pita_hummus', name: 'Pitabroodje Hummus', kcal: 280, unitName: '120 G' },
  { id: 'l_sushi_maki', name: 'Sushi (Maki 6 stuks)', kcal: 180, unitName: '150 G' },
  { id: 'l_kip_corne', name: 'Kip Corné', kcal: 310, unitName: '150 G' },
  { id: 'l_garnalencocktail', name: 'Garnalencocktail', kcal: 150, unitName: '150 G' },
  { id: 'l_rundvleessalade', name: 'Rundvleessalade', kcal: 280, unitName: '150 G' },
  { id: 'l_aardappelsalade', name: 'Aardappelsalade', kcal: 250, unitName: '150 G' },
  { id: 'l_soep_pompoen', name: 'Pompoensoep', kcal: 110, unitName: '250 ML' },
  { id: 'l_soep_champignon', name: 'Champignonsoep', kcal: 125, unitName: '250 ML' },
  { id: 'l_soep_mosterd', name: 'Mosterdsoep', kcal: 140, unitName: '250 ML' },
  { id: 'l_stokbrood_kruidenboter', name: 'Stokbroodje Kruidenboter', kcal: 210, unitName: '100 G' },
  { id: 'l_wrap_kebab', name: 'Kebab Wrap', kcal: 550, unitName: '250 G' },
  { id: 'l_turks_brood', name: 'Turks Brood (Kwart)', kcal: 280, unitName: '100 G' },
  { id: 'l_salade_carpaccio', name: 'Carpaccio Salade', kcal: 240, unitName: '200 G' },
  { id: 'l_broodje_warm_vlees', name: 'Broodje Warm Vlees', kcal: 490, unitName: '200 G' },
  { id: 'l_surinaams_kip', name: 'Surinaamse Broodje Kip', kcal: 380, unitName: '150 G' },
  { id: 'l_bami_soep', name: 'Bami Soep', kcal: 150, unitName: '300 ML' },
  { id: 'l_miso_ramen', name: 'Miso Ramen', kcal: 420, unitName: '400 ML' },
  { id: 'l_salade_caprese', name: 'Caprese Salade', kcal: 310, unitName: '250 G' },
  { id: 'l_salade_grieks', name: 'Griekse Salade', kcal: 280, unitName: '250 G' },
  { id: 'l_pasta_pesto', name: 'Pasta Salade Pesto', kcal: 390, unitName: '250 G' },
  { id: 'l_salade_bulgur', name: 'Bulgur Salade', kcal: 290, unitName: '250 G' },
  { id: 'l_broodje_brie', name: 'Broodje Brie', kcal: 450, unitName: '180 G' },
  { id: 'l_broodje_rosbief', name: 'Broodje Rosbief', kcal: 210, unitName: '120 G' },
  { id: 'l_omelet_champignon', name: 'Omelet Champignon', kcal: 230, unitName: '150 G' },
  { id: 'l_knakworstjes', name: 'Knakworstjes (3 stuks)', kcal: 180, unitName: '60 G' },
  { id: 'l_bol_wit', name: 'Zachte Witte Bol', kcal: 140, unitName: '50 G' },
  { id: 'l_kaiserbroodje', name: 'Kaiserbroodje', kcal: 160, unitName: '60 G' },
  { id: 'l_taco_shells', name: 'Taco Shells (3 stuks)', kcal: 150, unitName: '45 G' },
  { id: 'l_burrito_vega', name: 'Burrito Vegetarisch', kcal: 480, unitName: '250 G' },
  { id: 'l_enchilada_kip', name: 'Enchilada Kip', kcal: 520, unitName: '300 G' },
  { id: 'l_quesadilla', name: 'Quesadilla Kaas', kcal: 380, unitName: '150 G' },
  { id: 'l_pannenkoek_ui', name: 'Lente-ui Pannenkoek', kcal: 210, unitName: '100 G' },
  { id: 'l_sashimi', name: 'Sashimi Mix', kcal: 160, unitName: '150 G' },
  { id: 'l_edamame_l', name: 'Edamame Bonen', kcal: 120, unitName: '100 G' },
  { id: 'l_soep_zuurkool', name: 'Zuurkoolsoep', kcal: 95, unitName: '250 ML' },
  { id: 'l_soep_kip', name: 'Kippensoep', kcal: 110, unitName: '250 ML' },
  { id: 'l_soep_uien', name: 'Franse Uiensoep', kcal: 150, unitName: '250 ML' },
  { id: 'l_gazpacho', name: 'Gazpacho', kcal: 85, unitName: '250 ML' },
  { id: 'l_soep_asperge', name: 'Aspergesoep', kcal: 105, unitName: '250 ML' },
  { id: 'l_broodje_makreel', name: 'Broodje Makreel', kcal: 340, unitName: '150 G' },
  { id: 'l_broodje_haring', name: 'Broodje Haring', kcal: 280, unitName: '120 G' },
  { id: 'l_salade_forel', name: 'Gerookte Forel Salade', kcal: 210, unitName: '200 G' },
  { id: 'l_salade_waldorf', name: 'Waldorf Salade', kcal: 290, unitName: '200 G' },
  { id: 'l_pokebowl_tofu', name: 'Poke Bowl Tofu', kcal: 450, unitName: '400 G' },
  { id: 'l_roti_roll', name: 'Roti Roll', kcal: 580, unitName: '350 G' },
  { id: 'l_tosti_hawaii', name: 'Tosti Hawaii', kcal: 290, unitName: '130 G' },
  { id: 'l_knakworst_vega', name: 'Knakworst (Vegetarisch)', kcal: 140, unitName: '60 G' },
  { id: 'l_broodje_oude_kaas', name: 'Broodje Oude Kaas', kcal: 410, unitName: '150 G' },
  { id: 'l_pistolet_filet', name: 'Pistoletje Filet Americain', kcal: 320, unitName: '130 G' },
  { id: 'l_gevuld_ei_l', name: 'Gevuld Ei (2 stuks)', kcal: 150, unitName: '80 G' },
  { id: 'l_garnalenkroket', name: 'Garnalenkroket', kcal: 180, unitName: '80 G' },
  { id: 'l_bitterballen', name: 'Bitterballen (5 stuks)', kcal: 230, unitName: '100 G' },
];

const DINNER_LIST: MealOption[] = [
  { id: 'm_macaroni', name: 'Macaroni Bolognese', kcal: 650, unitName: '450 G' },
  { id: 'm_pizza_mar', name: 'Pizza Margherita', kcal: 850, unitName: '350 G' },
  { id: 'm_hutspot', name: 'Hutspot met klapstuk', kcal: 550, unitName: '500 G' },
  { id: 'm_zalmmoot', name: 'Zalmmoot', kcal: 200, unitName: '100 G' },
  { id: 'm_stamppot_boerenkool', name: 'Stamppot Boerenkool', kcal: 500, unitName: '500 G' },
  { id: 'm_lasagne', name: 'Lasagne Bolognese', kcal: 680, unitName: '400 G' },
  { id: 'm_sushi_box', name: 'Sushi Box', kcal: 520, unitName: '250 G' },
  { id: 'm_biefstuk_friet', name: 'Biefstuk met Friet', kcal: 750, unitName: '500 G' },
  { id: 'm_spaghetti_carb', name: 'Spaghetti Carbonara', kcal: 720, unitName: '400 G' },
  { id: 'm_risotto_pad', name: 'Risotto met Paddenstoelen', kcal: 550, unitName: '350 G' },
  { id: 'm_kip_tandoori', name: 'Kip Tandoori met Rijst', kcal: 610, unitName: '450 G' },
  { id: 'm_runderstoof', name: 'Runderstoofpot', kcal: 480, unitName: '350 G' },
  { id: 'm_varkenshaas', name: 'Varkenshaas Champignonsaus', kcal: 350, unitName: '200 G' },
  { id: 'm_kabeljauw_oven', name: 'Kabeljauw uit de oven', kcal: 180, unitName: '150 G' },
  { id: 'm_gevulde_paprika', name: 'Gevulde Paprika (Gehakt)', kcal: 320, unitName: '300 G' },
  { id: 'm_groene_curry', name: 'Thaise Groene Curry', kcal: 580, unitName: '450 G' },
  { id: 'm_nasi_goreng', name: 'Nasi Goreng met Ei', kcal: 590, unitName: '400 G' },
  { id: 'm_bami_goreng', name: 'Bami Goreng met Saté', kcal: 680, unitName: '450 G' },
  { id: 'm_moussaka', name: 'Moussaka', kcal: 620, unitName: '400 G' },
  { id: 'm_ravioli_ricotta', name: 'Ravioli Ricotta/Spinazie', kcal: 450, unitName: '250 G' },
  { id: 'm_hachee', name: 'Hachee', kcal: 420, unitName: '300 G' },
  { id: 'm_zuurkoolstamppot', name: 'Zuurkoolstamppot met Worst', kcal: 580, unitName: '500 G' },
  { id: 'm_andijviestamppot', name: 'Andijviestamppot met Spek', kcal: 540, unitName: '500 G' },
  { id: 'm_gado_gado', name: 'Gado Gado', kcal: 410, unitName: '350 G' },
  { id: 'm_pasta_pesto', name: 'Pasta Pesto met Kip', kcal: 640, unitName: '400 G' },
  { id: 'm_shoarma_pita', name: 'Shoarma met Pita', kcal: 650, unitName: '300 G' },
  { id: 'm_friet_mayo', name: 'Friet met Mayonaise', kcal: 520, unitName: '200 G' },
  { id: 'm_kipschnitzel', name: 'Kipschnitzel', kcal: 280, unitName: '120 G' },
  { id: 'm_wiener_schnitzel', name: 'Wiener Schnitzel', kcal: 340, unitName: '150 G' },
  { id: 'm_chili_carne', name: 'Chili con Carne', kcal: 480, unitName: '400 G' },
  { id: 'm_chili_sin_carne', name: 'Chili sin Carne', kcal: 390, unitName: '400 G' },
  { id: 'm_ratatouille', name: 'Ratatouille', kcal: 180, unitName: '300 G' },
  { id: 'm_paella', name: 'Paella', kcal: 550, unitName: '400 G' },
  { id: 'm_tortellini_bouillon', name: 'Tortellini in Bouillon', kcal: 320, unitName: '350 ML' },
  { id: 'm_gnocchi', name: 'Gnocchi Tomatensaus', kcal: 420, unitName: '300 G' },
  { id: 'm_lamskotelet', name: 'Lamskoteletjes (2 stuks)', kcal: 310, unitName: '150 G' },
  { id: 'm_eendenborst', name: 'Eendenborst', kcal: 260, unitName: '100 G' },
  { id: 'm_tongfilet', name: 'Tongfilet Gebakken', kcal: 190, unitName: '150 G' },
  { id: 'm_forel_oven', name: 'Forel uit de oven', kcal: 210, unitName: '200 G' },
  { id: 'm_mosselen', name: 'Mosselen (Pan)', kcal: 350, unitName: '500 G' },
  { id: 'm_garnalen_wok', name: 'Garnalen uit de Wok', kcal: 160, unitName: '150 G' },
  { id: 'm_quiche_lorraine', name: 'Quiche Lorraine', kcal: 480, unitName: '200 G' },
  { id: 'm_zweedse_ballen', name: 'Zweedse Gehaktballen', kcal: 410, unitName: '200 G' },
  { id: 'm_goulash', name: 'Goulash', kcal: 440, unitName: '350 G' },
  { id: 'm_hertenbiefstuk', name: 'Hertenbiefstuk', kcal: 150, unitName: '100 G' },
  { id: 'm_kip_marengo', name: 'Kip Marengo', kcal: 480, unitName: '400 G' },
  { id: 'm_ossobuco', name: 'Ossobuco', kcal: 520, unitName: '350 G' },
  { id: 'm_varkensrollade', name: 'Varkensrollade', kcal: 280, unitName: '150 G' },
  { id: 'm_kalkoenfilet', name: 'Kalkoenfilet Gebakken', kcal: 160, unitName: '100 G' },
  { id: 'm_zwaardvis', name: 'Zwaardvissteak', kcal: 190, unitName: '150 G' },
  { id: 'm_inktvisringen', name: 'Inktvisringen', kcal: 340, unitName: '150 G' },
  { id: 'm_wieners_grill', name: 'Wieners van de grill', kcal: 310, unitName: '150 G' },
  { id: 'm_hotwings', name: 'Kipvleugels (Hotwings)', kcal: 420, unitName: '200 G' },
  { id: 'm_spareribs', name: 'Spareribs (Gegrild)', kcal: 680, unitName: '350 G' },
  { id: 'm_vega_burger', name: 'Vegetarische Burger', kcal: 210, unitName: '100 G' },
  { id: 'm_falafel_set', name: 'Falafel (5 stuks)', kcal: 280, unitName: '125 G' },
  { id: 'm_tempeh_ketjap', name: 'Tempeh Ketjap', kcal: 190, unitName: '150 G' },
  { id: 'm_tofu_roerbak', name: 'Tofu Roerbak', kcal: 170, unitName: '200 G' },
  { id: 'm_seitan_steaks', name: 'Seitan Steaks', kcal: 180, unitName: '150 G' },
  { id: 'm_spruitjes_spek', name: 'Spruitjes met Spekjes', kcal: 160, unitName: '200 G' },
  { id: 'm_asperges_ham_ei', name: 'Asperges met Ham/Ei', kcal: 320, unitName: '400 G' },
  { id: 'm_courgette_vega', name: 'Gevulde Courgette (Vega)', kcal: 240, unitName: '300 G' },
  { id: 'm_enchiladas', name: 'Mexicaanse Enchiladas', kcal: 580, unitName: '350 G' },
  { id: 'm_tagliatelle_truffel', name: 'Tagliatelle Truffel', kcal: 540, unitName: '300 G' },
  { id: 'm_penne_arrabiata', name: 'Penne Arrabiata', kcal: 480, unitName: '350 G' },
  { id: 'm_fusilli_tonijn', name: 'Fusilli met Tonijn', kcal: 520, unitName: '400 G' },
  { id: 'm_couscous_lam', name: 'Couscous met Lamsvlees', kcal: 620, unitName: '450 G' },
  { id: 'm_siu_mai', name: 'Kip Siu Mai (8 stuks)', kcal: 320, unitName: '200 G' },
  { id: 'm_babi_pangang', name: 'Babi Pangang', kcal: 540, unitName: '350 G' },
  { id: 'm_foe_yong_hai', name: 'Foe Yong Hai', kcal: 480, unitName: '350 G' },
  { id: 'm_tjap_tjoy', name: 'Tjap Tjoy met Kip', kcal: 340, unitName: '400 G' },
  { id: 'm_rijsttafel', name: 'Indische Rijsttafel', kcal: 850, unitName: '600 G' },
  { id: 'm_boeuf_bourg', name: 'Boeuf Bourguignon', kcal: 510, unitName: '350 G' },
  { id: 'm_coq_au_vin', name: 'Coq au Vin', kcal: 490, unitName: '400 G' },
  { id: 'm_cassoulet', name: 'Cassoulet', kcal: 650, unitName: '450 G' },
];

const SNACKS_LIST_60: MealOption[] = [
  { id: 's_amandelen', name: 'Amandelen', kcal: 160, unitName: '25 G' },
  { id: 's_rijstwafel_hummus', name: 'Rijstwafel Hummus', kcal: 65, unitName: '30 G' },
  { id: 's_pure_choco', name: 'Pure Chocolade (85%)', kcal: 55, unitName: '10 G' },
  { id: 's_snoeptomaatjes', name: 'Snoeptomaatjes', kcal: 25, unitName: '100 G' },
  { id: 's_komkommer', name: 'Komkommer', kcal: 15, unitName: '100 G' },
  { id: 's_cracker_huttenkase', name: 'Cracker Hüttenkäse', kcal: 90, unitName: '40 G' },
  { id: 's_olijven_g', name: 'Olijven (Groen)', kcal: 45, unitName: '30 G' },
  { id: 's_olijven_z', name: 'Olijven (Zwart)', kcal: 55, unitName: '30 G' },
  { id: 's_gekookt_ei', name: 'Gekookt Ei', kcal: 75, unitName: '55 G' },
  { id: 's_walnoten', name: 'Walnoten', kcal: 170, unitName: '25 G' },
  { id: 's_kaas_48_b', name: 'Blokje Kaas (48+)', kcal: 80, unitName: '20 G' },
  { id: 's_kaas_30_b', name: 'Blokje Kaas (30+)', kcal: 60, unitName: '20 G' },
  { id: 's_pindas', name: "Pinda's (Gezouten)", kcal: 155, unitName: '25 G' },
  { id: 's_augurk', name: 'Augurk', kcal: 5, unitName: '30 G' },
  { id: 's_zoute_stengels', name: 'Zoute Stengels', kcal: 75, unitName: '20 G' },
  { id: 's_japanse_mix', name: 'Japanse Mix', kcal: 110, unitName: '25 G' },
  { id: 's_borrelnootjes', name: 'Borrelnootjes', kcal: 140, unitName: '25 G' },
  { id: 's_chips_nat', name: 'Chips (Naturel)', kcal: 135, unitName: '25 G' },
  { id: 's_chips_pap', name: 'Chips (Paprika)', kcal: 135, unitName: '25 G' },
  { id: 's_tortilla_chips', name: 'Tortilla Chips', kcal: 125, unitName: '25 G' },
  { id: 's_pretzels', name: 'Pretzels', kcal: 110, unitName: '30 G' },
  { id: 's_eierkoek', name: 'Eierkoek', kcal: 140, unitName: '50 G' },
  { id: 's_ontbijtkoek_s', name: 'Ontbijtkoek', kcal: 90, unitName: '30 G' },
  { id: 's_speculaasje', name: 'Speculaasje', kcal: 45, unitName: '10 G' },
  { id: 's_mariakaakje', name: 'Mariakaakje', kcal: 35, unitName: '8 G' },
  { id: 's_stroopwafel', name: 'Stroopwafel', kcal: 135, unitName: '30 G' },
  { id: 's_gevulde_koek', name: 'Gevulde Koek', kcal: 250, unitName: '55 G' },
  { id: 's_oat_cookies', name: 'Oat Cookies', kcal: 110, unitName: '25 G' },
  { id: 's_rijstwafel_choco', name: 'Rijstwafel Choco', kcal: 80, unitName: '15 G' },
  { id: 's_protein_bar', name: 'Protein Bar', kcal: 210, unitName: '55 G' },
  { id: 's_bifi', name: 'Bifi Worstje', kcal: 100, unitName: '20 G' },
  { id: 's_babybel', name: 'Mini Babybel', kcal: 60, unitName: '20 G' },
  { id: 's_dadelballetje', name: 'Dadelballetje', kcal: 85, unitName: '30 G' },
  { id: 's_kikkererwten_geroosterd', name: 'Geroosterde Kikkererwten', kcal: 120, unitName: '30 G' },
  { id: 's_gedroogde_mango', name: 'Gedroogde Mango', kcal: 95, unitName: '30 G' },
  { id: 's_gedroogde_abrikozen', name: 'Gedroogde Abrikozen', kcal: 75, unitName: '30 G' },
  { id: 's_popcorn_zout', name: 'Popcorn (Zout)', kcal: 90, unitName: '25 G' },
  { id: 's_popcorn_zoet', name: 'Popcorn (Zoet)', kcal: 115, unitName: '25 G' },
  { id: 's_rijstwafel_kaas', name: 'Rijstwafel (Kaas)', kcal: 45, unitName: '15 G' },
  { id: 's_paprika_reepjes', name: 'Paprika reepjes', kcal: 25, unitName: '100 G' },
  { id: 's_bleekselderij', name: 'Bleekselderij', kcal: 15, unitName: '100 G' },
  { id: 's_radijsjes', name: 'Radijsjes', kcal: 15, unitName: '100 G' },
  { id: 's_blokje_ham', name: 'Blokje Achterham', kcal: 35, unitName: '30 G' },
  { id: 's_kipfilet_rolletje', name: 'Rolletje Kipfilet', kcal: 25, unitName: '20 G' },
  { id: 's_sojabonen', name: 'Sojabonen (Edamame)', kcal: 120, unitName: '100 G' },
  { id: 's_kwark_honing_s', name: 'Kwark met Honing', kcal: 160, unitName: '150 G' },
  { id: 's_griekse_yoghurt_snack', name: 'Griekse Yoghurt', kcal: 180, unitName: '150 G' },
  { id: 's_rozijnen_s', name: 'Rozijnen', kcal: 90, unitName: '30 G' },
  { id: 's_pistachenoten_s', name: 'Pistachenoten', kcal: 145, unitName: '25 G' },
  { id: 's_pecannoten_snack', name: 'Pecannoten', kcal: 175, unitName: '25 G' },
  { id: 's_hazelnoten_snack', name: 'Hazelnoten', kcal: 165, unitName: '25 G' },
  { id: 's_paranoten', name: 'Paranoten', kcal: 185, unitName: '25 G' },
  { id: 's_macadamia', name: 'Macadamia noten', kcal: 195, unitName: '25 G' },
  { id: 's_cashewnoten_snack', name: 'Cashewnoten', kcal: 150, unitName: '25 G' },
  { id: 's_pompoenpitten_snack', name: 'Pompoenpitten', kcal: 90, unitName: '15 G' },
  { id: 's_zonnebloempitten_snack', name: 'Zonnebloempitten', kcal: 85, unitName: '15 G' },
  { id: 's_rijstwafel_appel', name: 'Rijstwafel Appel/Kaneel', kcal: 50, unitName: '15 G' },
  { id: 's_cracker_pindakaas', name: 'Cracker Pindakaas', kcal: 120, unitName: '30 G' },
  { id: 's_ontbijtkoek_zero', name: 'Ontbijtkoek Zero', kcal: 55, unitName: '30 G' },
  { id: 's_snack_wortel', name: 'Snackworteltjes', kcal: 35, unitName: '100 G' },
];

const FRUIT_LIST: MealOption[] = [
  { id: 'f_appel', name: 'Appel', kcal: 60, unitName: '150 G' },
  { id: 'f_banaan', name: 'Banaan', kcal: 105, unitName: '120 G' },
  { id: 'f_watermeloen', name: 'Watermeloen', kcal: 90, unitName: '300 G' },
  { id: 'f_druiven', name: 'Druiven', kcal: 105, unitName: '150 G' },
  { id: 'f_blauwe_bessen', name: 'Blauwe Bessen', kcal: 50, unitName: '100 G' },
  { id: 'f_peer', name: 'Peer', kcal: 75, unitName: '150 G' },
  { id: 'f_sinaasappel', name: 'Sinaasappel', kcal: 65, unitName: '150 G' },
  { id: 'f_kiwi', name: 'Kiwi', kcal: 40, unitName: '75 G' },
  { id: 'f_mango', name: 'Mango', kcal: 95, unitName: '150 G' },
  { id: 'f_aardbeien', name: 'Aardbeien', kcal: 45, unitName: '150 G' },
  { id: 'f_frambozen', name: 'Frambozen', kcal: 40, unitName: '100 G' },
  { id: 'f_bramen', name: 'Bramen', kcal: 45, unitName: '100 G' },
  { id: 'f_ananas', name: 'Ananas', kcal: 75, unitName: '150 G' },
  { id: 'f_perzik', name: 'Perzik', kcal: 50, unitName: '120 G' },
  { id: 'f_nectarine', name: 'Nectarine', kcal: 55, unitName: '120 G' },
  { id: 'f_pruim', name: 'Pruim', kcal: 45, unitName: '100 G' },
  { id: 'f_abrikoos', name: 'Abrikoos', kcal: 25, unitName: '50 G' },
  { id: 'f_kersen', name: 'Kersen', kcal: 75, unitName: '150 G' },
  { id: 'f_cantaloupe', name: 'Meloen (Cantaloupe)', kcal: 60, unitName: '200 G' },
  { id: 'f_papaya', name: 'Papaya', kcal: 60, unitName: '150 G' },
  { id: 'f_passievrucht', name: 'Passievrucht', kcal: 20, unitName: '30 G' },
  { id: 'f_vijgen', name: 'Vijgen (Vers)', kcal: 40, unitName: '50 G' },
  { id: 'f_dadels_gedroogd', name: 'Dadels (Gedroogd)', kcal: 60, unitName: '20 G' },
  { id: 'f_rozijnen_f', name: 'Rozijnen', kcal: 90, unitName: '30 G' },
];

export const MEAL_OPTIONS: Record<MealMoment, MealOption[]> = {
  'Ontbijt': [
    ...NON_ALC_DRINKS,
    ...BREAKFAST_LIST
  ],
  'Ochtend Snack': [
    ...NON_ALC_DRINKS,
    ...SNACKS_LIST_60,
    ...FRUIT_LIST
  ],
  'Lunch': [
    ...NON_ALC_DRINKS,
    ...LUNCH_LIST
  ],
  'Middag Snack': [
    ...NON_ALC_DRINKS,
    ...ALCOHOL_DRINKS,
    ...SNACKS_LIST_60,
    ...FRUIT_LIST
  ],
  'Diner': [
    ...NON_ALC_DRINKS,
    ...ALCOHOL_DRINKS,
    ...DINNER_LIST
  ],
  'Avond Snack': [
    ...NON_ALC_DRINKS,
    ...ALCOHOL_DRINKS,
    ...SNACKS_LIST_60,
    ...FRUIT_LIST
  ],
};

export const ACTIVITY_TYPES: ActivityType[] = [
  { id: 'act_wandelen_slow', name: 'Wandelen (Rustig)', met: 3.5, unit: 'minuten' },
  { id: 'act_wandelen_brisk', name: 'Wandelen (Stevig)', met: 4.5, unit: 'minuten' },
  { id: 'act_hardlopen_8', name: 'Hardlopen (8 km/u)', met: 8.3, unit: 'minuten' },
  { id: 'act_hardlopen_10', name: 'Hardlopen (10 km/u)', met: 10.0, unit: 'minuten' },
  { id: 'act_fietsen_rustig', name: 'Fietsen (Stads)', met: 6.0, unit: 'minuten' },
  { id: 'act_fietsen_tempo', name: 'Fietsen (Snel)', met: 10.0, unit: 'minuten' },
  { id: 'act_zwemmen', name: 'Zwemmen (Baantjes)', met: 6.0, unit: 'minuten' },
  { id: 'act_padel', name: 'Padel (Wedstrijd)', met: 8.0, unit: 'minuten' },
  { id: 'act_fitness', name: 'Fitness (Krachttraining)', met: 5.0, unit: 'minuten' },
  { id: 'act_voetbal', name: 'Voetbal (Training)', met: 8.0, unit: 'minuten' },
  { id: 'act_yoga', name: 'Yoga (Vinyasa)', met: 3.3, unit: 'minuten' },
  { id: 'act_tuinieren', name: 'Tuinieren', met: 4.0, unit: 'minuten' },
  { id: 'act_schoonmaken', name: 'Schoonmaken', met: 3.5, unit: 'minuten' },
  { id: 'act_koken', name: 'Koken', met: 2.0, unit: 'minuten' },
  { id: 'act_dansen', name: 'Dansen', met: 4.8, unit: 'minuten' },
  { id: 'act_crossfit', name: 'Crossfit', met: 12.0, unit: 'minuten' },
  { id: 'act_boksen', name: 'Boksen', met: 9.0, unit: 'minuten' },
  { id: 'act_golf', name: 'Golf (Lopen)', met: 4.8, unit: 'minuten' },
  { id: 'act_hiken', name: 'Hiken', met: 7.0, unit: 'minuten' },
  { id: 'act_roeien', name: 'Roeien', met: 7.0, unit: 'minuten' },
  { id: 'act_skien', name: 'Skiën', met: 6.0, unit: 'minuten' },
  { id: 'act_schaatsen', name: 'Schaatsen', met: 7.0, unit: 'minuten' },
  { id: 'act_klimmen', name: 'Klimmen', met: 8.0, unit: 'minuten' },
  { id: 'act_squash', name: 'Squash', met: 12.0, unit: 'minuten' },
  { id: 'act_volleybal', name: 'Volleybal', met: 4.0, unit: 'minuten' },
  { id: 'act_badminton', name: 'Badminton', met: 4.5, unit: 'minuten' },
  { id: 'act_tafeltennis', name: 'Tafeltennis', met: 4.0, unit: 'minuten' },
  { id: 'act_basketbal', name: 'Basketbal', met: 8.0, unit: 'minuten' },
  { id: 'act_staan_werk', name: 'Staand werk', met: 1.5, unit: 'minuten' },
  { id: 'act_aerobics', name: 'Aerobics', met: 7.3, unit: 'minuten' },
  { id: 'act_pilates', name: 'Pilates', met: 3.0, unit: 'minuten' },
  { id: 'act_spinnen', name: 'Spinning', met: 8.5, unit: 'minuten' },
  { id: 'act_bootcamp', name: 'Bootcamp', met: 10.0, unit: 'minuten' },
  { id: 'act_wandelen_hond', name: 'Hond uitlaten', met: 3.0, unit: 'minuten' },
  { id: 'act_trap_lopen', name: 'Traplopen', met: 8.0, unit: 'minuten' },
  { id: 'act_klussen', name: 'Klussen', met: 4.5, unit: 'minuten' },
  { id: 'act_verhuizen', name: 'Verhuizen', met: 7.0, unit: 'minuten' },
  { id: 'act_paardrijden', name: 'Paardrijden', met: 4.5, unit: 'minuten' }
];

export const KCAL_PER_KG_FAT = 7700;
