
import { MealOption, ActivityType, MealMoment, Language } from './types';

export const MEAL_MOMENTS: MealMoment[] = [
  'Ontbijt',
  'Ochtend snack',
  'Lunch',
  'Middag snack',
  'Diner',
  'Avondsnack'
];

export const PRODUCT_TRANSLATIONS: Record<Language, Record<string, string>> = {
  nl: {
    d_water: 'Water (Bronwater)',
    d_koffie: 'Koffie (Zwart)',
    d_thee: 'Thee (Groen/Zwart)',
    d_melk_half: 'Melk (Halfvol)',
    d_melk_vol: 'Melk (Vol)',
    d_sap_vers: 'Sinaasappelsap (Vers)',
    d_cola_zero: 'Cola Zero',
    b_skyr: 'Skyr Natuur (IJslands)',
    b_griekse_yoghurt: 'Griekse Yoghurt (10%)',
    b_magere_kwark: 'Magere Kwark (Eiwitrijk)',
    b_havermout: 'Havermout (Pap)',
    b_muesli: 'Muesli (Vruchten)',
    b_granola: 'Granola (Honing)',
    b_crusli: 'Crusli (Chocolade)',
    b_volkoren_brood: 'Volkoren Brood',
    b_waldkorn_brood: 'Waldkorn Brood',
    b_spelt_brood: 'Spelt Brood',
    b_ei_gekookt: 'Ei (Gekookt, L)',
    b_banaan: 'Banaan (Gemiddeld)',
    b_appel: 'Appel (Elstar)',
    b_ontbijtkoek: 'Ontbijtkoek (Plak)',
    b_blauwe_bessen: 'Blauwe Bessen (Vers)',
    l_soep_tomaat: 'Tomatensoep (Vers)',
    l_wrap_zalm: 'Wrap (Zalm & Roomkaas)',
    l_wrap_kip: 'Wrap (Kip & Avocado)',
    l_salade_caesar: 'Caesar Salade (Maaltijd)',
    l_uitsmijter: 'Uitsmijter (3 eieren)',
    l_tosti: 'Tosti (Ham/Kaas)',
    l_broodje_gezond: 'Broodje Gezond',
    l_krentenbol: 'Krentenbol',
    m_macaroni: 'Macaroni (Bolognese)',
    m_spaghetti: 'Spaghetti (Bolognese)',
    m_pizza_margherita: 'Pizza (Margherita)',
    m_hutspot: 'Hutspot (Klapstuk)',
    m_aardappel_gekookt: 'Aardappels (Gekookt)',
    m_aardappel_gebakken: 'Aardappels (Gebakken)',
    m_kip_filet: 'Kipfilet (Gebraden)',
    m_biefstuk: 'Biefstuk (Mager)',
    m_zalm: 'Zalmmoot (Gegrild)',
    m_broccoli: 'Broccoli (Gestoomd)',
    m_stamppot_boerenkool: 'Stamppot (Boerenkool)',
    act_wandelen_slow: 'Wandelen (Rustig)',
    act_wandelen_brisk: 'Wandelen (Stevig)',
    act_hardlopen_8: 'Hardlopen (8 km/u)',
    act_hardlopen_10: 'Hardlopen (10 km/u)',
    act_fietsen_rustig: 'Fietsen (Stads)',
    act_fietsen_tempo: 'Fietsen (Snel)',
    act_zwemmen: 'Zwemmen (Baantjes)',
    act_padel: 'Padel (Wedstrijd)',
    act_fitness: 'Fitness (Training)',
    act_voetbal: 'Voetbal (Training)',
    act_yoga: 'Yoga (Flow)',
    act_tuinieren: 'Tuinieren (Zwaar)',
    act_schoonmaken: 'Schoonmaken (Huis)',
    act_koken: 'Koken (Maaltijd)',
    act_dansen: 'Dansen (Pop)',
    act_crossfit: 'Crossfit (WOD)',
    act_boksen: 'Boksen (Zak)',
    act_golf: 'Golf (Lopen)',
    act_hiken: 'Hiken (Natuur)',
    act_roeien: 'Roeien (Middel)',
    act_skien: 'Skiën (Afdaal)',
    act_schaatsen: 'Schaatsen (Rondjes)',
    act_klimmen: 'Klimmen (Muur)',
    act_squash: 'Squash (Intens)',
    act_volleybal: 'Volleybal',
    act_badminton: 'Badminton',
    act_tafeltennis: 'Tafeltennis',
    act_basketbal: 'Basketbal',
    act_staan_werk: 'Staand werk',
    act_aerobics: 'Aerobics',
    act_pilates: 'Pilates',
    act_spinnen: 'Spinning',
    act_bootcamp: 'Bootcamp',
    act_wandelen_hond: 'Hond uitlaten',
    act_trap_lopen: 'Traplopen',
    act_klussen: 'Klussen (Huis)',
    act_verhuizen: 'Verhuizen',
    act_paardrijden: 'Paardrijden'
  },
  en: {
    d_water: 'Water (Spring)',
    d_koffie: 'Coffee (Black)',
    d_thee: 'Tea (Green/Black)',
    d_melk_half: 'Milk (Semi-skimmed)',
    d_melk_vol: 'Milk (Whole)',
    d_sap_vers: 'Orange Juice (Fresh)',
    d_cola_zero: 'Cola Zero',
    b_skyr: 'Skyr (Icelandic)',
    b_griekse_yoghurt: 'Greek Yogurt (10%)',
    b_magere_kwark: 'Quark (High Protein)',
    b_havermout: 'Oats (Water)',
    b_muesli: 'Muesli (Fruit)',
    b_granola: 'Granola (Honey)',
    b_crusli: 'Crusli (Choco)',
    b_volkoren_brood: 'Whole Wheat Bread',
    b_waldkorn_brood: 'Waldkorn Bread',
    b_spelt_brood: 'Spelt Bread',
    b_ei_gekookt: 'Egg (Boiled, L)',
    b_banaan: 'Banana (Medium)',
    b_appel: 'Apple (Fresh)',
    b_ontbijtkoek: 'Gingerbread',
    b_blauwe_bessen: 'Blueberries (Fresh)',
    l_soep_tomaat: 'Tomato Soup',
    l_wrap_zalm: 'Salmon Wrap',
    l_wrap_kip: 'Chicken Wrap',
    l_salade_caesar: 'Caesar Salad',
    l_uitsmijter: 'Fried Eggs (3)',
    l_tosti: 'Grilled Cheese',
    l_broodje_gezond: 'Healthy Sub',
    l_krentenbol: 'Currant Bun',
    m_macaroni: 'Macaroni',
    m_spaghetti: 'Spaghetti',
    m_pizza_margherita: 'Pizza',
    m_hutspot: 'Carrot & Potato Mash',
    m_aardappel_gekookt: 'Potatoes (Boiled)',
    m_aardappel_gebakken: 'Potatoes (Fried)',
    m_kip_filet: 'Chicken Breast',
    m_biefstuk: 'Beef Steak',
    m_zalm: 'Salmon Fillet',
    m_broccoli: 'Broccoli',
    m_stamppot_boerenkool: 'Kale Mash',
    act_wandelen_slow: 'Walking (Casual)',
    act_wandelen_brisk: 'Walking (Fast)',
    act_hardlopen_8: 'Running (8 km/h)',
    act_hardlopen_10: 'Running (10 km/h)',
    act_fietsen_rustig: 'Cycling (Casual)',
    act_fietsen_tempo: 'Cycling (Fast)',
    act_zwemmen: 'Swimming',
    act_padel: 'Padel',
    act_fitness: 'Fitness',
    act_voetbal: 'Football',
    act_yoga: 'Yoga',
    act_tuinieren: 'Gardening',
    act_schoonmaken: 'Cleaning',
    act_koken: 'Cooking',
    act_dansen: 'Dancing',
    act_crossfit: 'Crossfit',
    act_boksen: 'Boxing',
    act_golf: 'Golf',
    act_hiken: 'Hiking',
    act_roeien: 'Rowing',
    act_skien: 'Skiing',
    act_schaatsen: 'Ice Skating',
    act_klimmen: 'Climbing',
    act_squash: 'Squash',
    act_volleybal: 'Volleyball',
    act_badminton: 'Badminton',
    act_tafeltennis: 'Table Tennis',
    act_basketbal: 'Basketball',
    act_staan_werk: 'Standing Work',
    act_aerobics: 'Aerobics',
    act_pilates: 'Pilates',
    act_spinnen: 'Spinning',
    act_bootcamp: 'Bootcamp',
    act_wandelen_hond: 'Walking Dog',
    act_trap_lopen: 'Stairs',
    act_klussen: 'DIY Work',
    act_verhuizen: 'Moving House',
    act_paardrijden: 'Horse Riding'
  },
  es: {}, de: {}, pt: {}, zh: {}, ja: {}, ko: {}, hi: {}, ar: {}
};

const COMMON_DRINKS: MealOption[] = [
  { id: 'd_water', name: 'Water', kcal: 0, isDrink: true, unitName: '250 ML' },
  { id: 'd_koffie', name: 'Koffie (Zwart)', kcal: 2, isDrink: true, unitName: '200 ML' },
  { id: 'd_thee', name: 'Thee (Zonder suiker)', kcal: 2, isDrink: true, unitName: '200 ML' },
  { id: 'd_melk_half', name: 'Melk (Halfvol)', kcal: 115, isDrink: true, unitName: '250 ML' },
  { id: 'd_sap_vers', name: 'Sinaasappelsap (Vers)', kcal: 115, isDrink: true, unitName: '250 ML' },
  { id: 'd_cola_zero', name: 'Cola Zero', kcal: 0, isDrink: true, unitName: '250 ML' },
];

export const MEAL_OPTIONS: Record<MealMoment, MealOption[]> = {
  'Ontbijt': [
    ...COMMON_DRINKS,
    { id: 'b_skyr', name: 'Skyr Natuur', kcal: 95, unitName: '150G' },
    { id: 'b_griekse_yoghurt', name: 'Griekse Yoghurt (10%)', kcal: 180, unitName: '150G' },
    { id: 'b_magere_kwark', name: 'Magere Kwark', kcal: 140, unitName: '250G' },
    { id: 'b_havermout', name: 'Havermout (Water)', kcal: 130, unitName: '200G' },
    { id: 'b_muesli', name: 'Muesli Natuur', kcal: 145, unitName: '40G' },
    { id: 'b_granola', name: 'Granola (Krokant)', kcal: 190, unitName: '40G' },
    { id: 'b_crusli', name: 'Crusli Chocolade', kcal: 210, unitName: '45G' },
    { id: 'b_volkoren_brood', name: 'Volkoren Brood', kcal: 80, unitName: '1 SNEE (35G)' },
    { id: 'b_ei_gekookt', name: 'Ei (Gekookt)', kcal: 75, unitName: '1 STUK (50G)' },
    { id: 'b_banaan', name: 'Banaan', kcal: 105, unitName: '1 STUK (100G)' },
  ],
  'Ochtend snack': [
    ...COMMON_DRINKS,
    { id: 'b_ontbijtkoek', name: 'Ontbijtkoek', kcal: 65, unitName: '1 PLAK (30G)' },
    { id: 'b_appel', name: 'Appel', kcal: 60, unitName: '1 STUK (100G)' },
    { id: 'b_blauwe_bessen', name: 'Blauwe bessen', kcal: 50, unitName: '100G' },
  ],
  'Lunch': [
    ...COMMON_DRINKS,
    { id: 'l_soep_tomaat', name: 'Tomatensoep', kcal: 80, unitName: '1 KOM (250ML)' },
    { id: 'l_wrap_zalm', name: 'Wrap met Zalm', kcal: 320, unitName: '1 STUK (150G)' },
    { id: 'l_wrap_kip', name: 'Wrap met Kip', kcal: 300, unitName: '1 STUK (150G)' },
    { id: 'l_salade_caesar', name: 'Caesar Salade', kcal: 450, unitName: '1 MAALTIJD (350G)' },
    { id: 'l_uitsmijter', name: 'Uitsmijter (3 eieren)', kcal: 480, unitName: '1 BORD' },
    { id: 'l_tosti', name: 'Tosti Ham/Kaas', kcal: 260, unitName: '1 STUK (120G)' },
    { id: 'l_broodje_gezond', name: 'Broodje Gezond', kcal: 380, unitName: '1 STUK (200G)' },
  ],
  'Middag snack': [
    ...COMMON_DRINKS,
    { id: 'b_beschuit', name: 'Beschuit', kcal: 40, unitName: '1 STUK' },
    { id: 'b_knackebrod', name: 'Knäckebröd', kcal: 35, unitName: '1 STUK' },
  ],
  'Diner': [
    ...COMMON_DRINKS,
    { id: 'm_macaroni', name: 'Macaroni Bolognese', kcal: 650, unitName: '1 BORD (450G)' },
    { id: 'm_spaghetti', name: 'Spaghetti Bolognese', kcal: 700, unitName: '1 BORD (450G)' },
    { id: 'm_pizza_margherita', name: 'Pizza Margherita', kcal: 850, unitName: '1 STUK (350G)' },
    { id: 'm_hutspot', name: 'Hutspot met klapstuk', kcal: 550, unitName: '1 BORD (500G)' },
    { id: 'm_aardappel_gekookt', name: 'Aardappels (Gekookt)', kcal: 120, unitName: '150G' },
    { id: 'm_aardappel_gebakken', name: 'Aardappels (Gebakken)', kcal: 240, unitName: '150G' },
    { id: 'm_kip_filet', name: 'Kipfilet (Gebraden)', kcal: 165, unitName: '100G' },
    { id: 'm_biefstuk', name: 'Biefstuk', kcal: 180, unitName: '100G' },
    { id: 'm_zalm', name: 'Zalmmoot', kcal: 200, unitName: '100G' },
    { id: 'm_broccoli', name: 'Broccoli', kcal: 50, unitName: '150G' },
    { id: 'm_stamppot_boerenkool', name: 'Stamppot Boerenkool', kcal: 500, unitName: '1 BORD (500G)' },
  ],
  'Avondsnack': [
    ...COMMON_DRINKS,
    { id: 'b_ontbijtkoek', name: 'Ontbijtkoek', kcal: 65, unitName: '1 PLAK (30G)' },
  ],
};

export const ACTIVITY_TYPES: ActivityType[] = [
  { id: 'act_wandelen_slow', name: 'Wandelen (Rustig)', met: 3.5, unit: 'minuten' },
  { id: 'act_wandelen_brisk', name: 'Wandelen (Stevig)', met: 4.5, unit: 'minuten' },
  { id: 'act_hardlopen_8', name: 'Hardlopen (8 km/u)', met: 8.3, unit: 'minuten' },
  { id: 'act_hardlopen_10', name: 'Hardlopen (10 km/u)', met: 10.0, unit: 'minuten' },
  { id: 'act_fietsen_rustig', name: 'Fietsen (Stads)', met: 6.0, unit: 'minuten' },
  { id: 'act_fietsen_tempo', name: 'Fietsen (Snel)', met: 10.0, unit: 'minuten' },
  { id: 'act_zwemmen', name: 'Zwemmen (Baantjes)', met: 6.0, unit: 'minuten' },
  { id: 'act_padel', name: 'Padel (Wedstrijd)', met: 8.0, unit: 'minuten' },
  { id: 'act_fitness', name: 'Fitness (Krachttraining)', met: 5.0, unit: 'minuten' },
  { id: 'act_voetbal', name: 'Voetbal (Training)', met: 8.0, unit: 'minuten' },
  { id: 'act_yoga', name: 'Yoga (Vinyasa)', met: 3.3, unit: 'minuten' },
  { id: 'act_tuinieren', name: 'Tuinieren (Onderhoud)', met: 4.0, unit: 'minuten' },
  { id: 'act_schoonmaken', name: 'Schoonmaken', met: 3.5, unit: 'minuten' },
  { id: 'act_koken', name: 'Koken', met: 2.0, unit: 'minuten' },
  { id: 'act_dansen', name: 'Dansen', met: 4.8, unit: 'minuten' },
  { id: 'act_crossfit', name: 'Crossfit', met: 12.0, unit: 'minuten' },
  { id: 'act_boksen', name: 'Boksen', met: 9.0, unit: 'minuten' },
  { id: 'act_golf', name: 'Golf (Lopen)', met: 4.8, unit: 'minuten' },
  { id: 'act_hiken', name: 'Hiken', met: 7.0, unit: 'minuten' },
  { id: 'act_roeien', name: 'Roeien', met: 7.0, unit: 'minuten' },
  { id: 'act_skien', name: 'Skiën', met: 6.0, unit: 'minuten' },
  { id: 'act_schaatsen', name: 'Schaatsen', met: 7.0, unit: 'minuten' },
  { id: 'act_klimmen', name: 'Klimmen', met: 8.0, unit: 'minuten' },
  { id: 'act_squash', name: 'Squash', met: 12.0, unit: 'minuten' },
  { id: 'act_volleybal', name: 'Volleybal', met: 4.0, unit: 'minuten' },
  { id: 'act_badminton', name: 'Badminton', met: 4.5, unit: 'minuten' },
  { id: 'act_tafeltennis', name: 'Tafeltennis', met: 4.0, unit: 'minuten' },
  { id: 'act_basketbal', name: 'Basketbal', met: 8.0, unit: 'minuten' },
  { id: 'act_staan_werk', name: 'Staand werk', met: 1.5, unit: 'minuten' },
  { id: 'act_aerobics', name: 'Aerobics', met: 7.3, unit: 'minuten' },
  { id: 'act_pilates', name: 'Pilates', met: 3.0, unit: 'minuten' },
  { id: 'act_spinnen', name: 'Spinning', met: 8.5, unit: 'minuten' },
  { id: 'act_bootcamp', name: 'Bootcamp', met: 10.0, unit: 'minuten' },
  { id: 'act_wandelen_hond', name: 'Hond uitlaten', met: 3.0, unit: 'minuten' },
  { id: 'act_trap_lopen', name: 'Traplopen', met: 8.0, unit: 'minuten' },
  { id: 'act_klussen', name: 'Klussen', met: 4.5, unit: 'minuten' },
  { id: 'act_verhuizen', name: 'Verhuizen', met: 7.0, unit: 'minuten' },
  { id: 'act_paardrijden', name: 'Paardrijden', met: 4.5, unit: 'minuten' }
];

export const KCAL_PER_KG_FAT = 7700;
